// apps/dinoconfig_builder/src/app/pages/Settings.tsx
import React, { useState, useEffect } from 'react';
import './Settings.scss';
import axios from 'axios';
import { environment } from '../../environments';
import { useFeatures } from '../hooks/useFeatures';
import { Feature } from '../types/features';
import { FeatureBadge } from '../components';
import { subscriptionService } from '../services/subscription.service';

interface ApiKey {
  id: number;
  name: string;
  description?: string;
  isActive: boolean;
  lastUsedAt?: string;
  expiresAt?: string;
  createdAt: string;
  updatedAt: string;
}

interface ApiKeyList {
  keys: ApiKey[];
  total: number;
  active: number;
}

export default function Settings() {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['general', 'builder', 'export', 'sdk', 'features']));
  const [apiKeys, setApiKeys] = useState<ApiKeyList | null>(null);
  const [generatedApiKey, setGeneratedApiKey] = useState<{ key: string; name: string } | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [newKeyName, setNewKeyName] = useState('');
  const [newKeyDescription, setNewKeyDescription] = useState('');
  const [notification, setNotification] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const { subscription, hasFeature, loading: featuresLoading } = useFeatures();

  const toggleSection = (section: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(section)) {
      newExpanded.delete(section);
    } else {
      newExpanded.add(section);
    }
    setExpandedSections(newExpanded);
  };

  const showNotification = (type: 'success' | 'error', message: string) => {
    setNotification({ type, message });
    setTimeout(() => setNotification(null), 5000);
  };

  const fetchApiKeys = async () => {
    try {
      const response = await axios.get(`${environment.apiUrl}/api-keys`, { withCredentials: true });
      setApiKeys(response.data);
    } catch (error) {
      console.error('Failed to fetch API keys:', error);
    }
  };

  const createApiKey = async () => {
    if (!newKeyName.trim()) {
      showNotification('error', 'Please enter a name for the API key.');
      return;
    }

    setIsGenerating(true);
    try {
      const response = await axios.post(
        `${environment.apiUrl}/api-keys`,
        { name: newKeyName, description: newKeyDescription },
        { withCredentials: true }
      );
      setGeneratedApiKey({ key: response.data.key, name: response.data.name });
      setNewKeyName('');
      setNewKeyDescription('');
      setShowCreateForm(false);
      await fetchApiKeys();
      showNotification('success', 'API key created successfully! Make sure to copy it - you won\'t be able to see it again.');
    } catch (error: any) {
      console.error('Failed to create API key:', error);
      const message = error.response?.data?.message || 'Failed to create API key. Please try again.';
      showNotification('error', message);
    } finally {
      setIsGenerating(false);
    }
  };

  const revokeApiKey = async (id: number, name: string) => {
    if (!confirm(`Are you sure you want to revoke "${name}"? This action cannot be undone and will break any applications using this key.`)) {
      return;
    }

    try {
      await axios.post(`${environment.apiUrl}/api-keys/${id}/revoke`, {}, { withCredentials: true });
      await fetchApiKeys();
      showNotification('success', 'API key revoked successfully.');
    } catch (error) {
      console.error('Failed to revoke API key:', error);
      showNotification('error', 'Failed to revoke API key. Please try again.');
    }
  };

  const deleteApiKey = async (id: number, name: string) => {
    if (!confirm(`Are you sure you want to delete "${name}"? This action cannot be undone.`)) {
      return;
    }

    try {
      await axios.delete(`${environment.apiUrl}/api-keys/${id}`, { withCredentials: true });
      await fetchApiKeys();
      showNotification('success', 'API key deleted successfully.');
    } catch (error) {
      console.error('Failed to delete API key:', error);
      showNotification('error', 'Failed to delete API key. Please try again.');
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text).then(() => {
      showNotification('success', 'API key copied to clipboard!');
    }).catch((error) => {
      console.error('Failed to copy:', error);
      showNotification('error', 'Failed to copy to clipboard.');
    });
  };

  useEffect(() => {
    fetchApiKeys();
  }, []);

  return (
    <div className="settings-page">
      <div className="main-layout">
        <div className="settings-header">
          <div className="header-content">
            <h1 className="page-title">Settings</h1>
            <p className="page-subtitle">Manage your application preferences and configurations</p>
          </div>
        </div>

        <div className="main-content">
          <div className="settings-container">
            <div className="settings-content">
              
              <div className="settings-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('general')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('general') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  {/* <span className="section-icon">⚙️</span> */}
                  <span className="section-title">General Settings</span>
                </button>
                
                {expandedSections.has('general') && (
                <div className="settings-grid">
                  <div className="setting-item">
                    <label className="setting-label">Theme</label>
                    <select className="setting-control">
                      <option value="light">Light</option>
                      <option value="dark">Dark</option>
                      <option value="auto">Auto</option>
                    </select>
                  </div>
                  
                  <div className="setting-item">
                    <label className="setting-label">Language</label>
                    <select className="setting-control">
                      <option value="en">English</option>
                      <option value="es">Spanish</option>
                      <option value="fr">French</option>
                    </select>
                  </div>
                  
                  <div className="setting-item">
                    <label className="setting-label">Notifications</label>
                    <div className="setting-control">
                      <label className="checkbox-label">
                        <input type="checkbox" defaultChecked />
                        Email notifications
                      </label>
                      <label className="checkbox-label">
                        <input type="checkbox" defaultChecked />
                        Browser notifications
                      </label>
                    </div>
                  </div>
                </div>
                )}
              </div>

              <div className="settings-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('builder')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('builder') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  {/* <span className="section-icon">🔧</span> */}
                  <span className="section-title">Builder Settings</span>
                </button>
                
                {expandedSections.has('builder') && (
                <div className="settings-grid">
                  <div className="setting-item">
                    <label className="setting-label">Auto-save</label>
                    <div className="setting-control">
                      <label className="checkbox-label">
                        <input type="checkbox" defaultChecked />
                        Enable auto-save
                      </label>
                    </div>
                  </div>
                  
                  <div className="setting-item">
                    <label className="setting-label">Auto-save interval</label>
                    <select className="setting-control">
                      <option value="30">30 seconds</option>
                      <option value="60">1 minute</option>
                      <option value="300">5 minutes</option>
                    </select>
                  </div>
                  
                  <div className="setting-item">
                    <label className="setting-label">Default field type</label>
                    <select className="setting-control">
                      <option value="text">Text</option>
                      <option value="textarea">Textarea</option>
                      <option value="select">Select</option>
                    </select>
                  </div>
                </div>
                )}
              </div>

              <div className="settings-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('export')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('export') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  {/* <span className="section-icon">📤</span> */}
                  <span className="section-title">Export Settings</span>
                </button>
                
                {expandedSections.has('export') && (
                <div className="settings-grid">
                  <div className="setting-item">
                    <label className="setting-label">Default export format</label>
                    <select className="setting-control">
                      <option value="json">JSON</option>
                      <option value="yaml">YAML</option>
                      <option value="xml">XML</option>
                    </select>
                  </div>
                  
                  <div className="setting-item">
                    <label className="setting-label">Include metadata</label>
                    <div className="setting-control">
                      <label className="checkbox-label">
                        <input type="checkbox" defaultChecked />
                        Include schema metadata
                      </label>
                      <label className="checkbox-label">
                        <input type="checkbox" />
                        Include UI schema
                      </label>
                    </div>
                  </div>
                </div>
                )}
              </div>

              <div className="settings-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('features')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('features') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  <span className="section-title">Features & Subscription</span>
                </button>
                
                {expandedSections.has('features') && (
                <div className="settings-grid">
                  <div className="setting-item features-section">
                    {featuresLoading ? (
                      <div className="features-loading">Loading features...</div>
                    ) : subscription ? (
                      <>
                        <div className="subscription-info">
                          <div className="subscription-tier">
                            <span className="tier-label">Current Plan:</span>
                            <span className={`tier-badge tier-${subscription.tier}`}>
                              {subscriptionService.getTierDisplayName(subscription.tier)}
                            </span>
                            {subscription.status !== 'active' && subscription.status !== 'trialing' && (
                              <span className="status-warning">({subscription.status})</span>
                            )}
                          </div>
                          <div className="subscription-limits">
                            <div className="limit-item">
                              <span className="limit-label">Brands:</span>
                              <span className="limit-value">
                                {subscription.limits.maxBrands === -1 ? 'Unlimited' : subscription.limits.maxBrands}
                              </span>
                            </div>
                            <div className="limit-item">
                              <span className="limit-label">Configs per Brand:</span>
                              <span className="limit-value">
                                {subscription.limits.maxConfigsPerBrand === -1 ? 'Unlimited' : subscription.limits.maxConfigsPerBrand}
                              </span>
                            </div>
                          </div>
                        </div>

                        <div className="features-list">
                          <h4>Available Features</h4>
                          <div className="features-grid">
                            {Object.values(Feature).map((feature) => {
                              const isEnabled = hasFeature(feature);
                              const description = subscriptionService.getFeatureDescription(feature);
                              
                              // Determine which tier this feature belongs to
                              let featureTier: 'free' | 'starter' | 'pro' | 'custom' = 'free';
                              if (feature === Feature.BASIC_CONFIGS || feature === Feature.BASIC_SDK) {
                                featureTier = 'free';
                              } else if ([Feature.MULTIPLE_BRANDS, Feature.CONFIG_VERSIONING, Feature.WEBHOOKS, Feature.ANALYTICS].includes(feature)) {
                                featureTier = 'starter';
                              } else if ([Feature.UNLIMITED_BRANDS, Feature.UNLIMITED_CONFIGS, Feature.CONFIG_ROLLBACK, Feature.ADVANCED_SDK, Feature.API_RATE_LIMIT_INCREASED, Feature.ADVANCED_TARGETING, Feature.USER_SEGMENTATION, Feature.AB_TESTING, Feature.ADVANCED_ANALYTICS, Feature.AUDIT_LOGS, Feature.TEAM_COLLABORATION, Feature.PRIORITY_SUPPORT].includes(feature)) {
                                featureTier = 'pro';
                              } else {
                                featureTier = 'custom';
                              }

                              return (
                                <div 
                                  key={feature} 
                                  className={`feature-item ${isEnabled ? 'enabled' : 'disabled'}`}
                                  title={description}
                                >
                                  <div className="feature-status">
                                    {isEnabled ? (
                                      <svg width="20" height="20" viewBox="0 0 20 20" fill="none" className="icon-enabled">
                                        <circle cx="10" cy="10" r="9" fill="#10b981" stroke="#059669" strokeWidth="2"/>
                                        <path d="M6 10L9 13L14 7" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                                      </svg>
                                    ) : (
                                      <svg width="20" height="20" viewBox="0 0 20 20" fill="none" className="icon-disabled">
                                        <circle cx="10" cy="10" r="9" fill="#e5e7eb" stroke="#d1d5db" strokeWidth="2"/>
                                        <path d="M7 10L13 10" stroke="#9ca3af" strokeWidth="2" strokeLinecap="round"/>
                                      </svg>
                                    )}
                                  </div>
                                  <div className="feature-info">
                                    <div className="feature-name">{description}</div>
                                    {!isEnabled && <FeatureBadge tier={featureTier} size="small" />}
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        </div>

                        {subscription.tier !== 'custom' && (
                          <div className="upgrade-prompt">
                            <h4>Want more features?</h4>
                            <p>Upgrade your plan to unlock additional capabilities for your configurations.</p>
                            <a href="/subscription" className="btn btn-primary">
                              View Plans & Upgrade
                            </a>
                          </div>
                        )}
                      </>
                    ) : (
                      <div className="features-error">
                        <p>Unable to load subscription features.</p>
                      </div>
                    )}
                  </div>
                </div>
                )}
              </div>

              <div className="settings-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('sdk')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('sdk') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  {/* <span className="section-icon">🔧</span> */}
                  <span className="section-title">SDK & API Keys</span>
                </button>
                
                {expandedSections.has('sdk') && (
                <div className="settings-grid">
                  <div className="setting-item api-key-section">
                    <label className="setting-label">API Keys</label>
                    <p className="setting-description">
                      Manage API keys to authenticate with the DinoConfig SDK. You can create multiple keys 
                      for different applications or environments.
                    </p>
                    
                    {notification && (
                      <div className={`notification notification-${notification.type}`}>
                        {notification.message}
                      </div>
                    )}

                    {generatedApiKey && (
                      <div className="api-key-display">
                        <h4>New API Key: {generatedApiKey.name}</h4>
                        <div className="api-key-value">
                          <code>{generatedApiKey.key}</code>
                          <button 
                            className="btn btn-icon" 
                            onClick={() => copyToClipboard(generatedApiKey.key)}
                            title="Copy to clipboard"
                          >
                            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                              <path d="M13.333 6h-6c-.736 0-1.333.597-1.333 1.333v6c0 .737.597 1.334 1.333 1.334h6c.737 0 1.334-.597 1.334-1.334v-6c0-.736-.597-1.333-1.334-1.333z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                              <path d="M3.333 10H2.667C2.313 10 2 9.687 2 9.333V2.667C2 2.313 2.313 2 2.667 2h6.666c.354 0 .667.313.667.667V3.333" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                            </svg>
                          </button>
                        </div>
                        <p className="api-key-warning">
                          ⚠️ Make sure to copy your API key now. You won't be able to see it again!
                        </p>
                        <button 
                          className="btn btn-outline" 
                          onClick={() => setGeneratedApiKey(null)}
                        >
                          Close
                        </button>
                      </div>
                    )}

                    {apiKeys && (
                      <div className="api-keys-section">
                        {apiKeys.keys.length > 0 && (
                          <div className="api-keys-header">
                            <h4>Your API Keys ({apiKeys.active} active / {apiKeys.total} total)</h4>
                            <button 
                              className="btn btn-primary" 
                              onClick={() => setShowCreateForm(!showCreateForm)}
                            >
                              + Create New Key
                            </button>
                          </div>
                        )}

                        {showCreateForm && (
                          <div className="api-key-create-form">
                            <div className="form-field">
                              <label>Key Name *</label>
                              <input 
                                type="text" 
                                placeholder="e.g., Production App"
                                value={newKeyName}
                                onChange={(e) => setNewKeyName(e.target.value)}
                                maxLength={100}
                              />
                            </div>
                            <div className="form-field">
                              <label>Description (optional)</label>
                              <input 
                                type="text" 
                                placeholder="What is this key for?"
                                value={newKeyDescription}
                                onChange={(e) => setNewKeyDescription(e.target.value)}
                                maxLength={500}
                              />
                            </div>
                            <div className="form-actions">
                              <button 
                                className="btn btn-primary" 
                                onClick={createApiKey}
                                disabled={isGenerating}
                              >
                                {isGenerating ? 'Creating...' : 'Create Key'}
                              </button>
                              <button 
                                className="btn btn-outline" 
                                onClick={() => {
                                  setShowCreateForm(false);
                                  setNewKeyName('');
                                  setNewKeyDescription('');
                                }}
                              >
                                Cancel
                              </button>
                            </div>
                          </div>
                        )}

                        {apiKeys.keys.length > 0 && apiKeys.keys.map((key) => (
                          <div key={key.id} className={`api-key-item ${!key.isActive ? 'inactive' : ''}`}>
                            <div className="api-key-item-header">
                              <div className="api-key-item-title">
                                <h5>{key.name}</h5>
                                {key.isActive ? (
                                  <span className="status-badge status-active">Active</span>
                                ) : (
                                  <span className="status-badge status-inactive">Inactive</span>
                                )}
                              </div>
                              <div className="api-key-item-actions">
                                {key.isActive && (
                                  <button 
                                    className="btn btn-sm btn-danger" 
                                    onClick={() => revokeApiKey(key.id, key.name)}
                                  >
                                    Revoke
                                  </button>
                                )}
                                <button 
                                  className="btn btn-sm btn-outline" 
                                  onClick={() => deleteApiKey(key.id, key.name)}
                                >
                                  Delete
                                </button>
                              </div>
                            </div>
                            {key.description && (
                              <p className="api-key-item-description">{key.description}</p>
                            )}
                            <div className="api-key-item-meta">
                              <span><strong>Created:</strong> {new Date(key.createdAt).toLocaleString()}</span>
                              {key.lastUsedAt ? (
                                <span><strong>Last used:</strong> {new Date(key.lastUsedAt).toLocaleString()}</span>
                              ) : (
                                <span><strong>Last used:</strong> Never</span>
                              )}
                            </div>
                          </div>
                        ))}

                        {apiKeys.keys.length === 0 && !showCreateForm && (
                          <div className="api-key-empty">
                            <p>You don't have any API keys yet.</p>
                            <button 
                              className="btn btn-primary" 
                              onClick={() => setShowCreateForm(true)}
                            >
                              Create Your First API Key
                            </button>
                          </div>
                        )}
                      </div>
                    )}

                    <div className="api-key-docs">
                      <h4>Usage Example</h4>
                      <pre><code>{`import { dinoconfigApi } from '@dinoconfig/js-sdk';

const dinoconfig = dinoconfigApi({
  apiKey: 'your-api-key-here',
  baseUrl: '${environment.apiUrl}',
});

// Ready to use! Token exchange happens automatically
const configs = await dinoconfig.configs.getAllConfigs(brandId);`}</code></pre>
                    </div>
                  </div>
                </div>
                )}
              </div>

              <div className="settings-actions">
                <button className="btn btn-primary">
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path d="M13.333 4L6 11.333 2.667 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  Save Settings
                </button>
                <button className="btn btn-outline">
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path d="M13.333 2.667v10.666M13.333 2.667L10 6m3.333-3.333L16.667 6M2.667 13.333V2.667M2.667 13.333L6 10m-3.333 3.333L-1 10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  Reset to Defaults
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// apps/dinoconfig-builder/src/app/components/settings/settings.component.ts
import { Component, signal, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, NavigationEnd } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { FormsModule } from '@angular/forms';
import { ApiKeyService } from '../../services/api-key.service';
import { SubscriptionService } from '../../services/subscription.service';
import { SubscriptionStatus } from '../../models/subscription.models';
import { ApiKeyList, CreateApiKeyRequest } from '../../models/api-key.models';
import { SpinnerComponent } from '../shared/spinner/spinner.component';
import { catchError, of, filter } from 'rxjs';

interface Notification {
  type: 'success' | 'error';
  message: string;
}

interface GeneratedApiKey {
  key: string;
  name: string;
}

@Component({
  selector: 'dc-settings',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    FormsModule,
    SpinnerComponent
  ],
  templateUrl: './settings.component.html',
  styleUrl: './settings.component.scss'
})
export class SettingsComponent implements OnInit {
  private router = inject(Router);
  private apiKeyService = inject(ApiKeyService);
  private subscriptionService = inject(SubscriptionService);

  subscription = signal<SubscriptionStatus | null>(null);
  isLoadingSubscription = signal(true);
  apiKeys = signal<ApiKeyList | null>(null);
  isLoadingApiKeys = signal(true);
  
  expandedSections = signal<Set<string>>(new Set());
  currentRoute = signal<string>('');
  
  generatedApiKey = signal<GeneratedApiKey | null>(null);
  showCreateForm = signal(false);
  isGenerating = signal(false);
  newKeyName = signal('');
  newKeyDescription = signal('');
  notification = signal<Notification | null>(null);

  ngOnInit(): void {
    this.loadSubscription();
    this.loadApiKeys();
    this.updateExpandedSections();
    
    this.router.events.pipe(
      filter(event => event instanceof NavigationEnd)
    ).subscribe(() => {
      this.updateExpandedSections();
    });
  }

  private updateExpandedSections(): void {
    const url = this.router.url;
    this.currentRoute.set(url);
    
    if (url === '/settings') {
      this.expandedSections.set(new Set(['sdk', 'features']));
    } else if (url === '/settings/sdk') {
      this.expandedSections.set(new Set(['sdk']));
    } else if (url === '/settings/features') {
      this.expandedSections.set(new Set(['features']));
    }
  }

  getPageTitle(): string {
    const route = this.currentRoute();
    if (route === '/settings/sdk') {
      return 'SDK & API Keys';
    } else if (route === '/settings/features') {
      return 'Features';
    }
    return 'Settings';
  }

  getPageSubtitle(): string {
    const route = this.currentRoute();
    if (route === '/settings/sdk') {
      return 'Manage SDK authentication keys for your apps';
    } else if (route === '/settings/features') {
      return 'Your plan and available capabilities';
    }
    return 'Manage your application preferences and configurations';
  }

  loadSubscription(): void {
    this.isLoadingSubscription.set(true);

    this.subscriptionService.getSubscriptionWithViolations().pipe(
      catchError(() => of(null))
    ).subscribe(data => {
      if (data) {
        this.subscription.set({
          tier: data.tier,
          status: data.status,
          limits: data.limits,
          features: data.features,
          currentPeriodEnd: data.currentPeriodEnd,
          isActive: data.isActive
        });
      }
      this.isLoadingSubscription.set(false);
    });
  }

  loadApiKeys(): void {
    this.isLoadingApiKeys.set(true);

    this.apiKeyService.getApiKeys().pipe(
      catchError(() => of(null))
    ).subscribe(data => {
      this.apiKeys.set(data);
      this.isLoadingApiKeys.set(false);
    });
  }

  toggleSection(section: string): void {
    const current = new Set(this.expandedSections());
    if (current.has(section)) {
      current.delete(section);
    } else {
      current.add(section);
    }
    this.expandedSections.set(current);
  }

  isExpanded(section: string): boolean {
    return this.expandedSections().has(section);
  }

  showNotification(type: 'success' | 'error', message: string): void {
    this.notification.set({ type, message });
    setTimeout(() => this.notification.set(null), 5000);
  }

  createApiKey(): void {
    if (!this.newKeyName().trim()) {
      this.showNotification('error', 'Please enter a name for the API key.');
      return;
    }

    this.isGenerating.set(true);
    const request: CreateApiKeyRequest = {
      name: this.newKeyName().trim(),
      description: this.newKeyDescription().trim() || undefined
    };

    this.apiKeyService.createApiKey(request).pipe(
      catchError((err: any) => {
        const message = err.error?.message || 'Failed to create API key. Please try again.';
        this.showNotification('error', message);
        return of(null);
      })
    ).subscribe(data => {
      if (data) {
        this.generatedApiKey.set({ key: data.key, name: data.name });
        this.newKeyName.set('');
        this.newKeyDescription.set('');
        this.showCreateForm.set(false);
        this.loadApiKeys();
        this.showNotification('success', 'API key created successfully! Make sure to copy it - you won\'t be able to see it again.');
      }
      this.isGenerating.set(false);
    });
  }

  revokeApiKey(id: number, name: string): void {
    if (!confirm(`Are you sure you want to revoke "${name}"? This action cannot be undone and will break any applications using this key.`)) {
      return;
    }

    this.apiKeyService.revokeApiKey(id).pipe(
      catchError(() => {
        this.showNotification('error', 'Failed to revoke API key. Please try again.');
        return of(null);
      })
    ).subscribe(() => {
      this.loadApiKeys();
      this.showNotification('success', 'API key revoked successfully.');
    });
  }

  deleteApiKey(id: number, name: string): void {
    if (!confirm(`Are you sure you want to delete "${name}"? This action cannot be undone.`)) {
      return;
    }

    this.apiKeyService.deleteApiKey(id).pipe(
      catchError(() => {
        this.showNotification('error', 'Failed to delete API key. Please try again.');
        return of(null);
      })
    ).subscribe(() => {
      this.loadApiKeys();
      this.showNotification('success', 'API key deleted successfully.');
    });
  }

  copyToClipboard(text: string): void {
    navigator.clipboard.writeText(text).then(() => {
      this.showNotification('success', 'API key copied to clipboard!');
    }).catch(() => {
      this.showNotification('error', 'Failed to copy to clipboard.');
    });
  }

  getTierDisplayName(tier: string): string {
    return this.subscriptionService.getTierDisplayName(tier);
  }

  getFeatureDescription(feature: string): string {
    return this.subscriptionService.getFeatureDescription(feature);
  }

  hasFeature(feature: string): boolean {
    const sub = this.subscription();
    if (!sub) return false;
    return this.subscriptionService.hasFeature(feature, sub);
  }

  getFeatureTier(feature: string): 'free' | 'starter' | 'pro' | 'custom' {
    if (feature === 'basic_configs' || feature === 'basic_sdk') {
      return 'free';
    } else if (['multiple_brands', 'multiple_configs'].includes(feature)) {
      return 'starter';
    } else if (['unlimited_brands', 'unlimited_configs', 'config_rollback', 'advanced_sdk', 'api_rate_limit_increased', 'advanced_targeting', 'user_segmentation', 'ab_testing', 'advanced_analytics', 'audit_logs', 'team_collaboration', 'priority_support'].includes(feature)) {
      return 'pro';
    } else {
      return 'custom';
    }
  }

  getAllFeatures(): string[] {
    return [
      'basic_configs',
      'basic_sdk',
      'multiple_configs',
      'unlimited_configs',
      'config_versioning',
      'config_rollback',
      'multiple_brands',
      'unlimited_brands',
      'advanced_sdk',
      'webhooks',
      'api_rate_limit_increased',
      'advanced_targeting',
      'user_segmentation',
      'ab_testing',
      'analytics',
      'advanced_analytics',
      'audit_logs',
      'team_collaboration',
      'role_based_access',
      'priority_support',
      'dedicated_support',
      'custom_integrations',
      'sso',
      'sla'
    ];
  }

  goToSubscription(): void {
    this.router.navigate(['/subscription']);
  }

  formatDateTime(dateString: string | undefined): string {
    if (!dateString) return 'Never';
    return new Date(dateString).toLocaleString();
  }
}


<div class="settings-page">
  <div class="main-layout">
    <div class="settings-header">
      <div class="header-content">
        <h1 class="page-title">{{ getPageTitle() }}</h1>
        <p class="page-subtitle">{{ getPageSubtitle() }}</p>
      </div>
    </div>

    <div class="main-content">
      <div class="settings-container">
        <div class="settings-content">
          
          @if (currentRoute() === '/settings' || currentRoute() === '/settings/sdk') {
            <div class="settings-section">
              <button 
                class="section-toggle"
                (click)="toggleSection('sdk')"
              >
                <mat-icon 
                  class="chevron"
                  [class.open]="isExpanded('sdk')"
                >
                  expand_more
                </mat-icon>
                <span class="section-title">SDK & API Keys</span>
              </button>
              
              @if (isExpanded('sdk')) {
              <div class="settings-grid">
                <div class="setting-item api-key-section">
                  <label class="setting-label">API Keys</label>
                  <p class="setting-description">
                    Manage API keys to authenticate with the DinoConfig SDK. You can create multiple keys 
                    for different applications or environments.
                  </p>
                  
                  @if (notification()) {
                    <div class="notification" [class.notification-success]="notification()!.type === 'success'" [class.notification-error]="notification()!.type === 'error'">
                      {{ notification()!.message }}
                    </div>
                  }

                  @if (generatedApiKey()) {
                    <div class="api-key-display">
                      <h4>New API Key: {{ generatedApiKey()!.name }}</h4>
                      <div class="api-key-value">
                        <code>{{ generatedApiKey()!.key }}</code>
                        <button 
                          class="btn btn-icon" 
                          (click)="copyToClipboard(generatedApiKey()!.key)"
                          title="Copy to clipboard"
                        >
                          <mat-icon>content_copy</mat-icon>
                        </button>
                      </div>
                      <p class="api-key-warning">
                        ⚠️ Make sure to copy your API key now. You won't be able to see it again!
                      </p>
                      <button 
                        class="btn btn-outline" 
                        (click)="generatedApiKey.set(null)"
                      >
                        Close
                      </button>
                    </div>
                  }

                  @if (isLoadingApiKeys()) {
                    <div class="flex items-center justify-center p-8">
                      <dc-spinner text="Loading API keys..." size="medium"></dc-spinner>
                    </div>
                  } @else if (apiKeys()) {
                    <div class="api-keys-section">
                      @if (apiKeys()!.keys.length > 0) {
                        <div class="api-keys-header">
                          <h4>Your API Keys ({{ apiKeys()!.active }} active / {{ apiKeys()!.total }} total)</h4>
                          <button 
                            class="btn btn-primary" 
                            (click)="showCreateForm.set(!showCreateForm())"
                          >
                            + Create New Key
                          </button>
                        </div>
                      }

                      @if (showCreateForm()) {
                        <div class="api-key-create-form">
                          <div class="form-field">
                            <label>Key Name *</label>
                            <input 
                              type="text" 
                              placeholder="e.g., Production App"
                              [value]="newKeyName()"
                              (input)="newKeyName.set($any($event.target).value)"
                              maxlength="100"
                            />
                          </div>
                          <div class="form-field">
                            <label>Description (optional)</label>
                            <input 
                              type="text" 
                              placeholder="What is this key for?"
                              [value]="newKeyDescription()"
                              (input)="newKeyDescription.set($any($event.target).value)"
                              maxlength="500"
                            />
                          </div>
                          <div class="form-actions">
                            <button 
                              class="btn btn-primary" 
                              (click)="createApiKey()"
                              [disabled]="isGenerating()"
                            >
                              {{ isGenerating() ? 'Creating...' : 'Create Key' }}
                            </button>
                            <button 
                              class="btn btn-outline" 
                              (click)="showCreateForm.set(false); newKeyName.set(''); newKeyDescription.set('')"
                            >
                              Cancel
                            </button>
                          </div>
                        </div>
                      }

                      @if (apiKeys()!.keys.length > 0) {
                        @for (key of apiKeys()!.keys; track key.id) {
                          <div class="api-key-item" [class.inactive]="!key.isActive">
                            <div class="api-key-item-header">
                              <div class="api-key-item-title">
                                <h5>{{ key.name }}</h5>
                                @if (key.isActive) {
                                  <span class="status-badge status-active">Active</span>
                                } @else {
                                  <span class="status-badge status-inactive">Inactive</span>
                                }
                              </div>
                              <div class="api-key-item-actions">
                                @if (key.isActive) {
                                  <button 
                                    class="btn btn-sm btn-danger" 
                                    (click)="revokeApiKey(key.id, key.name)"
                                  >
                                    Revoke
                                  </button>
                                }
                                <button 
                                  class="btn btn-sm btn-outline" 
                                  (click)="deleteApiKey(key.id, key.name)"
                                >
                                  Delete
                                </button>
                              </div>
                            </div>
                            @if (key.description) {
                              <p class="api-key-item-description">{{ key.description }}</p>
                            }
                            <div class="api-key-item-meta">
                              <span><strong>Created:</strong> {{ formatDateTime(key.createdAt) }}</span>
                              <span><strong>Last used:</strong> {{ formatDateTime(key.lastUsedAt) }}</span>
                            </div>
                          </div>
                        }
                      }

                      @if (apiKeys()!.keys.length === 0 && !showCreateForm()) {
                        <div class="api-key-empty">
                          <p>You don't have any API keys yet.</p>
                          <button 
                            class="btn btn-primary" 
                            (click)="showCreateForm.set(true)"
                          >
                            Create Your First API Key
                          </button>
                        </div>
                      }
                    </div>
                  }

                  <div class="api-key-docs">
                    <h4>Usage Example</h4>
                    <pre><code>import {{ '{' }} dinoconfigApi {{ '}' }} from '@dinoconfig/js-sdk';

const dinoconfig = dinoconfigApi({{ '{' }}
  apiKey: 'your-api-key-here',
  baseUrl: 'http://localhost:3000/api',
{{ '}' }});

// Ready to use! Token exchange happens automatically
const configs = await dinoconfig.configs.getAllConfigs(brandId);</code></pre>
                  </div>
                </div>
              </div>
            }
            </div>
          }

          @if (currentRoute() === '/settings' || currentRoute() === '/settings/features') {
            <div class="settings-section">
              <button 
                class="section-toggle"
                (click)="toggleSection('features')"
              >
                <mat-icon 
                  class="chevron"
                  [class.open]="isExpanded('features')"
                >
                  expand_more
                </mat-icon>
                <span class="section-title">Features</span>
              </button>
              
              @if (isExpanded('features')) {
                <div class="settings-grid">
                  <div class="setting-item features-section">
                    @if (isLoadingSubscription()) {
                      <div class="features-loading">Loading features...</div>
                    } @else if (subscription()) {
                      <div class="subscription-info">
                        <div class="subscription-tier">
                          <span class="tier-label">Current Plan:</span>
                          <span class="tier-badge" [class.tier-free]="subscription()!.tier === 'free'" [class.tier-starter]="subscription()!.tier === 'starter'" [class.tier-pro]="subscription()!.tier === 'pro'" [class.tier-custom]="subscription()!.tier === 'custom'">
                            {{ getTierDisplayName(subscription()!.tier) }}
                          </span>
                          @if (subscription()!.status !== 'active' && subscription()!.status !== 'trialing') {
                            <span class="status-warning">({{ subscription()!.status }})</span>
                          }
                        </div>
                        <div class="subscription-limits">
                          <div class="limit-item">
                            <span class="limit-label">Brands:</span>
                            <span class="limit-value">
                              {{ subscription()!.limits.maxBrands === -1 ? 'Unlimited' : subscription()!.limits.maxBrands }}
                            </span>
                          </div>
                          <div class="limit-item">
                            <span class="limit-label">Configs per Brand:</span>
                            <span class="limit-value">
                              {{ subscription()!.limits.maxConfigsPerBrand === -1 ? 'Unlimited' : subscription()!.limits.maxConfigsPerBrand }}
                            </span>
                          </div>
                        </div>
                      </div>

                      <div class="features-list">
                        <h4>Available Features</h4>
                        <div class="features-grid">
                          @for (feature of getAllFeatures(); track feature) {
                            <div class="feature-item" [class.enabled]="hasFeature(feature)" [class.disabled]="!hasFeature(feature)" [title]="getFeatureDescription(feature)">
                              <div class="feature-status">
                                @if (hasFeature(feature)) {
                                  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" class="icon-enabled">
                                    <circle cx="10" cy="10" r="9" fill="#10b981" stroke="#059669" stroke-width="2"/>
                                    <path d="M6 10L9 13L14 7" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                  </svg>
                                } @else {
                                  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" class="icon-disabled">
                                    <circle cx="10" cy="10" r="9" fill="#e5e7eb" stroke="#d1d5db" stroke-width="2"/>
                                    <path d="M7 10L13 10" stroke="#9ca3af" stroke-width="2" stroke-linecap="round"/>
                                  </svg>
                                }
                              </div>
                              <div class="feature-info">
                                <div class="feature-name">{{ getFeatureDescription(feature) }}</div>
                                @if (!hasFeature(feature)) {
                                  <span class="feature-badge" [class.badge-free]="getFeatureTier(feature) === 'free'" [class.badge-starter]="getFeatureTier(feature) === 'starter'" [class.badge-pro]="getFeatureTier(feature) === 'pro'" [class.badge-custom]="getFeatureTier(feature) === 'custom'">
                                    {{ getTierDisplayName(getFeatureTier(feature)) }}
                                  </span>
                                }
                              </div>
                            </div>
                          }
                        </div>
                      </div>

                      @if (subscription()!.tier !== 'custom') {
                        <div class="upgrade-prompt">
                          <h4>Want more features?</h4>
                          <p>Upgrade your plan to unlock additional capabilities for your configurations.</p>
                          <button class="btn btn-primary" (click)="goToSubscription()">
                            View Plans & Upgrade
                          </button>
                        </div>
                      }
                    } @else {
                      <div class="features-error">
                        <p>Unable to load subscription features.</p>
                      </div>
                    }
                  </div>
                </div>
              }
            </div>
          }
        </div>
      </div>
    </div>
  </div>
</div>
