// apps/dinoconfig_builder/src/app/brand-selection/brand-selection.tsx
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from "../auth/axios-interceptor";
import { environment } from "../../environments";
import { Spinner } from "../components";
import "./brand-selection.scss";
import { IoAdd } from "react-icons/io5";

interface Brand {
  id: number;
  name: string;
  description?: string;
  logo?: string;
  website?: string;
  createdAt: string;
}

export default function BrandSelection() {
  const navigate = useNavigate();
  const [brands, setBrands] = useState<Brand[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadBrands();
  }, []);

  const loadBrands = async () => {
    try {
      setIsLoading(true);
      setError(null);
      const response = await axios.get(`${environment.apiUrl}/brands`, {
        withCredentials: true
      });
      
      // Handle both array response and object with brands + limitViolations
      if (Array.isArray(response.data)) {
        setBrands(response.data);
      } else if (response.data.brands && Array.isArray(response.data.brands)) {
        setBrands(response.data.brands);
      } else {
        setBrands([]);
      }
    } catch (err) {
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || 'Failed to load brands');
      } else {
        setError('An error occurred');
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleBrandSelect = (brandId: number) => {
    try {
      if (typeof window !== 'undefined') {
        localStorage.setItem('lastBrandId', String(brandId));
      }
    } catch (_) {}
    navigate(`/brands/${brandId}/builder`);
  };

  const handleCreateNewBrand = () => {
    navigate('/brands/add');
  };

  if (isLoading) {
    return (
      <div className="brand-selection">
        <div className="brand-selection-container">
          <Spinner text="Loading your brands..." size="large" fullHeight />
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="brand-selection">
        <div className="brand-selection-container">
          <div className="error-state">
            <h2>Error loading brands</h2>
            <p>{error}</p>
            <button className="btn primary" onClick={loadBrands}>
              Try Again
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="brand-selection">
      <div className="brand-selection-container">
        <div className="header">
          <h1>Select Your Brand</h1>
          <p>Choose a brand to start building configurations</p>
        </div>

        {brands.length === 0 ? (
          <div className="empty-state">
            <div className="empty-icon">🏢</div>
            <h2>No brands yet</h2>
            <p>Create your first brand to get started with building configurations</p>
            <button className="btn primary" onClick={handleCreateNewBrand}>
              Create Your First Brand
            </button>
          </div>
        ) : (
          <>
            <div className="brands-grid">
              {brands.map((brand) => (
                <div key={brand.id} className="brand-card" onClick={() => handleBrandSelect(brand.id)}>
                  <div className="brand-logo">
                    {brand.logo ? (
                      <img src={brand.logo} alt={`${brand.name} logo`} />
                    ) : (
                      <div className="default-logo">
                        {brand.name.charAt(0).toUpperCase()}
                      </div>
                    )}
                  </div>
                  <div className="brand-info">
                    <h3>{brand.name}</h3>
                    {brand.description && (
                      <p className="brand-description">{brand.description}</p>
                    )}
                    <div className="brand-meta">
                      <span className="created-date">
                        Created {new Date(brand.createdAt).toLocaleDateString()}
                      </span>
                    </div>
                  </div>
                  <div className="brand-actions">
                    <button className="btn primary select-btn">
                      Select Brand
                    </button>
                  </div>
                </div>
              ))}
            </div>

            <div className="create-new-section">
              <button className="btn secondary" onClick={handleCreateNewBrand}>
                <IoAdd />
                Create New Brand
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// apps/dinoconfig-builder/src/app/components/brand-selection/brand-selection.component.ts
import { Component, signal, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { BrandService } from '../../services/brand.service';
import { Brand } from '../../models/user.models';
import { SpinnerComponent } from '../shared/spinner/spinner.component';
import { catchError, of } from 'rxjs';

@Component({
  selector: 'dc-brand-selection',
  standalone: true,
  imports: [CommonModule, RouterModule, MatButtonModule, MatIconModule, SpinnerComponent],
  templateUrl: './brand-selection.component.html',
  styleUrl: './brand-selection.component.scss'
})
export class BrandSelectionComponent implements OnInit {
  private router = inject(Router);
  private brandService = inject(BrandService);

  brands = signal<Brand[]>([]);
  isLoading = signal(true);
  error = signal<string | null>(null);

  ngOnInit(): void {
    this.loadBrands();
  }

  loadBrands(): void {
    this.isLoading.set(true);
    this.error.set(null);

    this.brandService.getBrands().pipe(
      catchError((err: any) => {
        this.error.set(err.error?.message || 'Failed to load brands');
        return of(null);
      })
    ).subscribe(data => {
      if (data) {
        // Handle both array response and object with brands
        if (Array.isArray(data)) {
          this.brands.set(data);
        } else if ('brands' in data && Array.isArray(data.brands)) {
          this.brands.set(data.brands);
        } else {
          this.brands.set([]);
        }
      }
      this.isLoading.set(false);
    });
  }

  handleBrandSelect(brandId: number): void {
    try {
      if (typeof window !== 'undefined') {
        localStorage.setItem('lastBrandId', String(brandId));
      }
    } catch (_) {}
    this.router.navigate(['/brands', brandId, 'builder']);
  }

  handleCreateNewBrand(): void {
    this.router.navigate(['/brands/add']);
  }

  formatDate(dateString?: string): string {
    if (!dateString) return '';
    return new Date(dateString).toLocaleDateString();
  }
}


<div class="brand-selection">
  <div class="brand-selection-container">
    @if (isLoading()) {
      <dc-spinner text="Loading your brands..." size="large" [fullHeight]="true"></dc-spinner>
    } @else if (error()) {
      <div class="error-state">
        <h2>Error loading brands</h2>
        <p>{{ error() }}</p>
        <button mat-raised-button color="primary" (click)="loadBrands()">
          Try Again
        </button>
      </div>
    } @else {
      <div class="header">
        <h1>Select Your Brand</h1>
        <p>Choose a brand to start building configurations</p>
      </div>

      @if (brands().length === 0) {
        <div class="empty-state">
          <div class="empty-icon">🏢</div>
          <h2>No brands yet</h2>
          <p>Create your first brand to get started with building configurations</p>
          <button mat-raised-button color="primary" (click)="handleCreateNewBrand()">
            Create Your First Brand
          </button>
        </div>
      } @else {
        <div class="brands-grid">
          @for (brand of brands(); track brand.id) {
            <div class="brand-card" (click)="handleBrandSelect(brand.id)">
              <div class="brand-logo">
                @if (brand.logo) {
                  <img [src]="brand.logo" [alt]="brand.name + ' logo'" />
                } @else {
                  <div class="default-logo">
                    {{ brand.name.charAt(0).toUpperCase() }}
                  </div>
                }
              </div>
              <div class="brand-info">
                <h3>{{ brand.name }}</h3>
                @if (brand.description) {
                  <p class="brand-description">{{ brand.description }}</p>
                }
                <div class="brand-meta">
                  @if (brand.createdAt) {
                    <span class="created-date">
                      Created {{ formatDate(brand.createdAt) }}
                    </span>
                  }
                </div>
              </div>
              <div class="brand-actions">
                <button mat-raised-button color="primary" class="select-btn">
                  Select Brand
                </button>
              </div>
            </div>
          }
        </div>

        <div class="create-new-section">
          <button mat-raised-button color="primary" (click)="handleCreateNewBrand()">
            <mat-icon>add</mat-icon>
            Create New Brand
          </button>
        </div>
      }
    }
  </div>
</div>
