// apps/dinoconfig-builder/src/app/components/navigation/left-navigation/left-navigation.component.ts
import { Component, input, signal, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule, NavigationEnd } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { UserService } from '../../../services/user.service';
import { SubscriptionService } from '../../../services/subscription.service';
import { AuthService } from '../../../services/auth.service';
import { environment } from '../../../../environments/environment';
import { User } from '../../../models/user.models';
import { SubscriptionStatus } from '../../../models/subscription.models';
import { catchError, of, filter } from 'rxjs';
import { SubscriptionTierBoxComponent } from '../../shared/subscription-tier-box/subscription-tier-box.component';
import { UserInfoComponent } from '../../shared/user-info/user-info.component';
import { NavMenuItemComponent } from '../../shared/nav-menu-item/nav-menu-item.component';

@Component({
  selector: 'dc-left-navigation',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    MatButtonModule,
    MatIconModule,
    SubscriptionTierBoxComponent,
    UserInfoComponent,
    NavMenuItemComponent
  ],
  templateUrl: './left-navigation.component.html',
  styleUrl: './left-navigation.component.scss'
})
export class LeftNavigationComponent implements OnInit {
  router = inject(Router);
  private userService = inject(UserService);
  private subscriptionService = inject(SubscriptionService);
  private authService = inject(AuthService);

  isCollapsed = input<boolean>(false);
  onToggle = input<() => void>(() => {});

  user = signal<User | null>(null);
  subscription = signal<SubscriptionStatus | null>(null);
  loading = signal<boolean>(true);

  currentPath = signal<string>('');

  ngOnInit(): void {
    this.loadUser();
    this.loadSubscription();

    this.router.events.pipe(
      filter(event => event instanceof NavigationEnd)
    ).subscribe(() => {
      this.currentPath.set(this.router.url);
    });
    
    this.currentPath.set(this.router.url);
  }

  private loadUser(): void {
    this.userService.getUser().pipe(
      catchError(() => of(null))
    ).subscribe(user => {
      this.user.set(user);
      this.loading.set(false);
    });
  }

  private loadSubscription(): void {
    this.subscriptionService.getSubscriptionWithViolations().pipe(
      catchError(() => of(null))
    ).subscribe(data => {
      if (data) {
        this.subscription.set({
          tier: data.tier,
          status: data.status,
          limits: data.limits,
          features: data.features,
          currentPeriodEnd: data.currentPeriodEnd,
          isActive: data.isActive
        });
      }
    });
  }

  goBuilder(): void {
    const lastBrandId = localStorage.getItem('lastBrandId');
    if (!lastBrandId) {
      this.router.navigate(['/brands']);
      return;
    }
    this.router.navigate(['/brands', lastBrandId, 'builder']);
  }

  goProfile(): void {
    this.router.navigate(['/profile']);
  }

  goSettings(): void {
    this.router.navigate(['/settings']);
  }

  goSettingsSdk(): void {
    this.router.navigate(['/settings/sdk']);
  }

  goSettingsFeatures(): void {
    this.router.navigate(['/settings/features']);
  }

  handleLogout(): void {
    localStorage.clear();
    sessionStorage.clear();

    this.authService.logout().subscribe({
      next: () => {
        window.location.href = environment.homeUrl;
      },
      error: () => {
        window.location.href = environment.homeUrl;
      }
    });
  }

  isActive(path: string): boolean {
    return this.currentPath().startsWith(path);
  }

  getActiveItem(): 'builder' | 'profile' | 'settings' {
    const path = this.currentPath();
    if (path.startsWith('/builder')) return 'builder';
    if (path.startsWith('/profile')) return 'profile';
    if (path.startsWith('/settings')) return 'settings';
    return 'builder';
  }
}

<div class="flex flex-col h-full overflow-hidden">
  <!-- Header -->
  <div class="p-6 pb-5 border-b border-gray-200 flex items-center justify-between relative flex-shrink-0 transition-all duration-300"
       [class.px-4]="isCollapsed()"
       [class.justify-center]="isCollapsed()">
    @if (isCollapsed()) {
      <img 
        src="/assets/dinoconfig-logo.svg" 
        alt="DinoConfig" 
        class="w-12 h-12 object-contain transition-all duration-200 cursor-pointer hover:scale-110 hover:brightness-110 active:scale-95"
        (click)="onToggle()()"
      />
    } @else {
      <h2 
        class="text-2xl font-bold text-gray-900 m-0 bg-gradient-to-br from-blue-600 to-purple-600 bg-clip-text text-transparent transition-opacity duration-200 whitespace-nowrap pr-2.5 cursor-pointer relative hover:opacity-80 hover:scale-[1.02] active:scale-[0.98] group"
        (click)="onToggle()()"
      >
        DinoConfig Builder
      </h2>
    }
  </div>

  <!-- Navigation Sections -->
  <div class="flex-1 py-5 overflow-y-auto overflow-x-hidden min-h-0">
    <!-- Main Section -->
    <div class="mb-8">
      <h3 class="text-xs font-semibold text-gray-500 uppercase tracking-[0.5px] m-0 mb-3 ml-5"
          [class.hidden]="isCollapsed()">
        Main
      </h3>
      <ul class="list-none p-0 m-0">
        <li class="mb-1">
          <dc-nav-menu-item
            icon="build"
            label="Builder"
            [isActive]="getActiveItem() === 'builder'"
            [isCollapsed]="isCollapsed()"
            (clicked)="goBuilder()"
          ></dc-nav-menu-item>
        </li>
      </ul>
    </div>

    <!-- Account Section -->
    <div class="mb-8">
      <h3 class="text-xs font-semibold text-gray-500 uppercase tracking-[0.5px] m-0 mb-3 ml-5"
          [class.hidden]="isCollapsed()">
        Account
      </h3>
      <ul class="list-none p-0 m-0">
        <li class="mb-1">
          <dc-nav-menu-item
            icon="person"
            label="Profile"
            [isActive]="getActiveItem() === 'profile'"
            [isCollapsed]="isCollapsed()"
            (clicked)="goProfile()"
          ></dc-nav-menu-item>
        </li>
        <li class="mb-1">
          <dc-nav-menu-item
            icon="settings"
            label="Settings"
            [isActive]="getActiveItem() === 'settings'"
            [isCollapsed]="isCollapsed()"
            [showArrow]="true"
            [arrowRotated]="isActive('/settings')"
            (clicked)="goSettings()"
          ></dc-nav-menu-item>
        </li>
        @if (!isCollapsed() && isActive('/settings')) {
          <li class="mb-1">
            <dc-nav-menu-item
              icon=""
              label="SDK & API Keys"
              [isActive]="isActive('/settings/sdk')"
              [isCollapsed]="isCollapsed()"
              [isSubItem]="true"
              (clicked)="goSettingsSdk()"
            ></dc-nav-menu-item>
          </li>
        }
        @if (!isCollapsed() && isActive('/settings')) {
          <li class="mb-1">
            <dc-nav-menu-item
              icon=""
              label="Features"
              [isActive]="isActive('/settings/features')"
              [isCollapsed]="isCollapsed()"
              [isSubItem]="true"
              (clicked)="goSettingsFeatures()"
            ></dc-nav-menu-item>
          </li>
        }
      </ul>
    </div>
  </div>

  <!-- Footer -->
  <div class="p-5 border-t border-gray-200 flex flex-col gap-4 flex-shrink-0 transition-all duration-300 overflow-hidden"
       [class.px-4]="isCollapsed()"
       [class.py-5]="isCollapsed()"
       [class.gap-3]="isCollapsed()">
    @if (!loading() && user() && subscription() && !isCollapsed()) {
      <dc-subscription-tier-box [subscription]="subscription()!"></dc-subscription-tier-box>
    }

    @if (!loading() && user()) {
      <dc-user-info [user]="user()!" [isCollapsed]="isCollapsed()"></dc-user-info>
    }
    
    <button 
      class="w-full flex items-center justify-center px-4 py-3 border-none rounded-lg bg-[#8b8b8b] text-white text-sm font-medium cursor-pointer transition-all duration-200 gap-2 hover:bg-[#454545] hover:-translate-y-0.5 hover:shadow-[0_4px_8px_rgba(239,68,68,0.3)] active:translate-y-0 active:shadow-[0_2px_4px_rgba(239,68,68,0.2)]"
      [class.w-10]="isCollapsed()"
      [class.h-10]="isCollapsed()"
      [class.p-2]="isCollapsed()"
      [class.text-[0]]="isCollapsed()"
      [class.m-0]="isCollapsed()"
      [class.flex-shrink-0]="isCollapsed()"
      [class.shadow-[0_2px_4px_rgba(0,0,0,0.1)]]="isCollapsed()"
      (click)="handleLogout()"
      [title]="isCollapsed() ? 'Logout' : ''"
    >
      <mat-icon class="w-[18px] h-[18px] text-lg flex-shrink-0 text-white"
                [class.mr-0]="isCollapsed()"
                [class.w-5]="isCollapsed()"
                [class.h-5]="isCollapsed()">
        logout
      </mat-icon>
      @if (!isCollapsed()) {
        <span class="text-white">Logout</span>
      }
    </button>
  </div>
</div>

// apps/dinoconfig_builder/src/app/navigation/left-navigation.tsx
import axios from "../auth/axios-interceptor";
import { useNavigate, useLocation } from "react-router-dom";
import { IoHammerOutline, IoPersonOutline, IoSettingsOutline, IoLogOutOutline } from "react-icons/io5";
import { useUser } from "../auth/user-context";
import { environment } from "../../environments";
import { useState, useEffect } from "react";
import { subscriptionService, SubscriptionStatus } from "../services/subscription.service";
import "./left-navigation.scss";

type LeftNavigationProps = {  
  isCollapsed: boolean;
  onToggle: () => void;
  activeItem: 'builder' | 'profile' | 'settings';
};

export default function LeftNavigation({ isCollapsed, onToggle, activeItem }: LeftNavigationProps) {
  const navigate = useNavigate();
  const location = useLocation();
  const { user, loading } = useUser();
  const [subscription, setSubscription] = useState<SubscriptionStatus | null>(null);

  const goBuilder = () => {
    const lastBrandId = localStorage.getItem('lastBrandId');

    if (!lastBrandId) {
      navigate(`/brands`);
      return;
    }

    navigate(`/brands/${lastBrandId}/builder`);
  };

  const goProfile = () => navigate(`/profile`);
  const goSettings = () => navigate(`/settings`);
  const goSettingsSdk = () => navigate(`/settings/sdk`);
  const goSettingsFeatures = () => navigate(`/settings/features`);

  const handleLogout = async () => {
    try {
      localStorage.clear();
      sessionStorage.clear();

      await axios.post(`${environment.apiUrl}/auth/logout`, {}, {
        withCredentials: true
      });

      window.location.href = environment.homeUrl;
    } catch (error) {
      console.error('Logout error:', error);
      window.location.href = environment.homeUrl;
    }
  };

  useEffect(() => {
    if (user && !loading) {
      loadSubscription();
    }
  }, [user, loading]);

  // Listen for subscription changes
  useEffect(() => {
    const handleSubscriptionChange = () => {
      if (user && !loading) {
        loadSubscription();
      }
    };

    window.addEventListener('subscriptionChanged', handleSubscriptionChange);
    
    return () => {
      window.removeEventListener('subscriptionChanged', handleSubscriptionChange);
    };
  }, [user, loading]);

  const loadSubscription = async () => {
    try {
      const status = await subscriptionService.getSubscriptionStatus();
      setSubscription(status);
    } catch (err) {
      console.error('Failed to load subscription:', err);
    }
  };

  const getUserDisplayName = () => {
    if (!user) return 'User';
    if (user.firstName && user.lastName) {
      return `${user.firstName} ${user.lastName}`;
    }
    if (user.firstName) return user.firstName;
    if (user.email) return user.email.split('@')[0];
    return 'User';
  };

  return (
    <nav className={`left-navigation ${isCollapsed ? 'collapsed' : ''}`}>
      <div className={`nav-header ${isCollapsed ? 'collapsed' : ''}`}>
        {isCollapsed ? (
          <img 
            src="assets/dinoconfig-logo.svg" 
            alt="DinoConfig" 
            className="nav-logo clickable-logo"
            onClick={onToggle}
          />
        ) : (
          <>
            <h2 
              className="nav-title-clickable"
              onClick={onToggle}
            >
              DinoConfig Builder
            </h2>
          </>
        )}
      </div>

      <div className="nav-sections">
        <div className="nav-section">
          <h3 className={`nav-section-title ${isCollapsed ? 'hidden' : ''}`}>Main</h3>
          <ul className="nav-menu">
            <li className="nav-item">
              <button 
                className={`nav-link ${activeItem === 'builder' ? 'active' : ''}`}
                onClick={goBuilder}
              >
                <IoHammerOutline className="nav-icon" />
                <span className={isCollapsed ? 'hidden' : ''}>Builder</span>
              </button>
            </li>
          </ul>
        </div>

        <div className="nav-section">
          <h3 className={`nav-section-title ${isCollapsed ? 'hidden' : ''}`}>Account</h3>
          <ul className="nav-menu">
            <li className="nav-item">
              <button 
                className={`nav-link ${activeItem === 'profile' ? 'active' : ''}`}
                onClick={goProfile}
              >
                <IoPersonOutline className="nav-icon" />
                <span className={isCollapsed ? 'hidden' : ''}>Profile</span>
              </button>
            </li>
            <li className="nav-item">
              <button 
                className={`nav-link ${activeItem === 'settings' ? 'active' : ''}`}
                onClick={goSettings}
              >
                <IoSettingsOutline className="nav-icon" />
                <span className={isCollapsed ? 'hidden' : ''}>Settings</span>
              </button>
            </li>
            {/* Settings child: Features (visible as nested under Settings) */}
            {!isCollapsed && location.pathname.startsWith('/settings') && (
              <li className="nav-item nav-subitem">
                <button 
                  className={`nav-link ${location.pathname.startsWith('/settings/sdk') ? 'active' : ''}`}
                  onClick={goSettingsSdk}
                  title={isCollapsed ? 'SDK & API Keys' : ''}
                >
                  <span className="nav-sub-bullet" />
                  <span className={isCollapsed ? 'hidden' : ''}>SDK & API Keys</span>
                </button>
              </li>
            )}
            {!isCollapsed && location.pathname.startsWith('/settings') && (
              <li className="nav-item nav-subitem">
                <button 
                  className={`nav-link ${location.pathname.startsWith('/settings/features') ? 'active' : ''}`}
                  onClick={goSettingsFeatures}
                  title={isCollapsed ? 'Features' : ''}
                >
                  <span className="nav-sub-bullet" />
                  <span className={isCollapsed ? 'hidden' : ''}>Features</span>
                </button>
              </li>
            )}
          </ul>
        </div>
      </div>

      {/* User info and logout section */}
      <div className="nav-footer">
        {!loading && user && subscription && !isCollapsed && (
          <div className="subscription-tier-box" onClick={() => navigate('/subscription')}>
            <div className="tier-info">
              <span className="tier-label">Current Plan</span>
              <span className={`tier-badge tier-badge--${subscription.tier}`}>
                {subscriptionService.getTierDisplayName(subscription.tier)}
              </span>
            </div>
            {subscription.tier === 'free' && (
              <button className="upgrade-btn-small">
                Upgrade to Pro
              </button>
            )}
          </div>
        )}

        {!loading && user && (
          <div className="user-info">
            <div className="user-avatar">
              {user.firstName ? user.firstName.charAt(0).toUpperCase() : 'U'}
            </div>
            <div className={`user-details ${isCollapsed ? 'hidden' : ''}`} onClick={goProfile}>
              <div className="user-name">{getUserDisplayName()}</div>
              <div className="user-email">{user.email}</div>
            </div>
          </div>
        )}
        
        <button 
          className="logout-button"
          onClick={handleLogout}
          title={isCollapsed ? 'Logout' : ''}
        >
          <IoLogOutOutline className="logout-icon" />
          <span className={isCollapsed ? 'hidden' : ''}>Logout</span>
        </button>
      </div>
    </nav>
  );
}
