// apps/dinoconfig_builder/src/app/components/subscription-limit-warning.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import './subscription-limit-warning.scss';

interface SubscriptionLimitWarningProps {
  message: string;
  currentTier: string;
}

export const SubscriptionLimitWarning: React.FC<SubscriptionLimitWarningProps> = ({ 
  message, 
  currentTier 
}) => {
  const navigate = useNavigate();

  const handleUpgrade = () => {
    navigate('/subscription');
  };

  return (
    <div className="subscription-limit-warning">
      <div className="subscription-limit-warning__icon">⚠️</div>
      <div className="subscription-limit-warning__content">
        <h3>Subscription Limit Reached</h3>
        <p>{message}</p>
        {currentTier === 'free' && (
          <button className="subscription-limit-warning__button" onClick={handleUpgrade}>
            Upgrade to Pro
          </button>
        )}
      </div>
    </div>
  );
};

// apps/dinoconfig-builder/src/app/components/shared/subscription-limit-warning/subscription-limit-warning.component.ts
import { Component, input, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'dc-subscription-limit-warning',
  standalone: true,
  imports: [CommonModule, MatButtonModule],
  templateUrl: './subscription-limit-warning.component.html',
  styleUrl: './subscription-limit-warning.component.scss'
})
export class SubscriptionLimitWarningComponent {
  private router = inject(Router);

  message = input.required<string>();
  currentTier = input.required<string>();

  handleUpgrade(): void {
    this.router.navigate(['/subscription']);
  }
}


<div class="flex items-start gap-4 p-5 bg-yellow-50 border border-yellow-400 rounded-lg mb-5">
  <div class="text-3xl flex-shrink-0">⚠️</div>
  <div class="flex-1">
    <h3 class="m-0 mb-2 text-lg font-semibold text-yellow-800">Subscription Limit Reached</h3>
    <p class="m-0 mb-3 text-sm text-yellow-800 leading-relaxed">{{ message() }}</p>
    @if (currentTier() === 'free') {
      <button mat-raised-button color="primary" (click)="handleUpgrade()">
        Upgrade to Pro
      </button>
    }
  </div>
</div>
