// apps/dinoconfig_builder/src/app/components/Spinner.tsx
import React from 'react';
import { ImSpinner2 } from 'react-icons/im';
import './Spinner.scss';

interface SpinnerProps {
  size?: 'small' | 'medium' | 'large';
  color?: string;
  text?: string;
  className?: string;
  fullHeight?: boolean;
}

const Spinner: React.FC<SpinnerProps> = ({ 
  size = 'medium', 
  color = '#007bff', 
  text, 
  className = '',
  fullHeight = false
}) => {
  const sizeMap = {
    small: '1rem',
    medium: '2rem',
    large: '3rem'
  };

  return (
    <div className={`spinner-container ${fullHeight ? 'full-height' : ''} ${className}`}>
      <ImSpinner2 
        className="spinner-icon" 
        style={{ 
          fontSize: sizeMap[size], 
          color: color 
        }} 
      />
      {text && <p className="spinner-text">{text}</p>}
    </div>
  );
};

export default Spinner;

// apps/dinoconfig-builder/src/app/components/shared/spinner/spinner.component.ts
import { Component, input, computed } from '@angular/core';

import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

@Component({
  selector: 'dc-spinner',
  standalone: true,
  imports: [MatProgressSpinnerModule],
  templateUrl: './spinner.component.html',
  styleUrl: './spinner.component.scss'
})
export class SpinnerComponent {
  size = input<'small' | 'medium' | 'large'>('medium');
  text = input<string>('');
  fullHeight = input<boolean>(false);

  spinnerDiameter = computed(() => {
    const sizeMap = {
      small: 24,
      medium: 40,
      large: 60
    };
    return sizeMap[this.size()];
  });
}


<div class="spinner-container" [class.full-height]="fullHeight()">
  <mat-spinner [diameter]="spinnerDiameter()"></mat-spinner>
  @if (text()) {
    <p class="spinner-text">{{ text() }}</p>
  }
</div>
