// apps/dinoconfig_builder/src/app/components/VersionSelector.tsx
import React, { useState, useEffect } from 'react';
import { Config } from '../types';
import { ConfigService } from '../services/configService';
import './VersionSelector.scss';

interface VersionSelectorProps {
  brandId: number;
  configId: number;
  configName: string;
  selectedVersion: number | null;
  onVersionSelect: (version: number) => void;
  onSetActiveVersion: (version: number) => void;
  activeVersion?: number;
  onNotification: (type: 'success' | 'error' | 'warning' | 'info', message: string) => void;
  versions?: Config[];
}

export const VersionSelector: React.FC<VersionSelectorProps> = ({
  brandId,
  configId,
  configName,
  selectedVersion,
  onVersionSelect,
  onSetActiveVersion,
  activeVersion,
  onNotification,
  versions = []
}) => {
  const [isSettingActive, setIsSettingActive] = useState(false);
  const [previewVersion, setPreviewVersion] = useState<Config | null>(null);
  const [isCollapsed, setIsCollapsed] = useState(true); // Start collapsed

  useEffect(() => {
    // Set the first version as preview by default when versions change
    if (versions.length > 0) {
      setPreviewVersion(versions[0]);
    }
  }, [versions]);

  const handleSetActiveVersion = async (version: number) => {
    try {
      setIsSettingActive(true);
      await ConfigService.setActiveVersion(brandId, configName, version);
      onSetActiveVersion(version);
      onNotification('success', `Version ${version} set as active`);
    } catch (error: any) {
      onNotification('error', 'Failed to set active version');
      console.error('Error setting active version:', error);
    } finally {
      setIsSettingActive(false);
    }
  };

  const handleVersionChange = (versionNumber: number) => {
    const version = versions.find(v => v.version === versionNumber);
    if (version) {
      setPreviewVersion(version);
      onVersionSelect(versionNumber);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (versions.length === 0) {
    return null;
  }

  return (
    <div className={`version-selector ${isCollapsed ? 'collapsed' : ''}`}>
      <div className="version-selector__header" onClick={() => setIsCollapsed(!isCollapsed)}>
        <h3>Version History</h3>
        <div className="version-selector__header-right">
          <div className="version-selector__active-indicator">
            <span className="version-selector__active-label">Active Version:</span>
            <span className="version-selector__active-version">v{activeVersion || 'Latest'}</span>
          </div>
          <button className="version-selector__collapse-toggle" aria-label={isCollapsed ? 'Expand' : 'Collapse'}>
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" style={{ transform: isCollapsed ? 'rotate(-90deg)' : 'rotate(0deg)', transition: 'transform 0.2s' }}>
              <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </button>
        </div>
      </div>
      
      {!isCollapsed && (
        <>
          <div className="version-selector__controls">
            <div className="version-selector__dropdown-container">
              <label htmlFor="version-select" className="version-selector__dropdown-label">
                Select Version to Preview:
              </label>
              <select
                id="version-select"
                className="version-selector__dropdown"
                value={previewVersion?.version || ''}
                onChange={(e) => handleVersionChange(Number(e.target.value))}
              >
                {versions.map((version) => (
                  <option key={version.id} value={version.version}>
                    v{version.version} - {formatDate(version.createdAt)}
                    {activeVersion === version.version ? ' (Active)' : ''}
                  </option>
                ))}
              </select>
            </div>
            
            <div className="version-selector__actions">
              <button
                className="version-selector__set-active-btn"
                onClick={() => previewVersion && handleSetActiveVersion(previewVersion.version)}
                disabled={isSettingActive || !!(previewVersion && activeVersion === previewVersion.version)}
              >
                {isSettingActive ? 'Setting...' : 'Set as Active Version'}
              </button>
            </div>
          </div>
          
          {previewVersion && (
            <div className="version-selector__preview">
              <div className="version-selector__preview-header">
                <h4>Preview - Version {previewVersion.version}</h4>
                <div className="version-selector__preview-date">
                  Created: {formatDate(previewVersion.createdAt)}
                </div>
                {activeVersion === previewVersion.version && (
                  <div className="version-selector__preview-active-badge">Currently Active</div>
                )}
              </div>
              
              {previewVersion.description && (
                <div className="version-selector__preview-description">
                  <strong>Description:</strong> {previewVersion.description}
                </div>
              )}
              
              <div className="version-selector__preview-data">
                <strong>Form Data:</strong>
                <pre className="version-selector__preview-json">
                  {JSON.stringify(previewVersion.formData, null, 2)}
                </pre>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
};

// apps/dinoconfig-builder/src/app/components/version-selector/version-selector.component.ts
import { Component, input, output, signal, effect, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatSelectModule } from '@angular/material/select';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { ConfigService } from '../../services/config.service';
import { Config } from '../../models/config.models';

@Component({
  selector: 'dc-version-selector',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatSelectModule,
    MatFormFieldModule,
    MatIconModule
  ],
  templateUrl: './version-selector.component.html',
  styleUrl: './version-selector.component.scss'
})
export class VersionSelectorComponent {
  private configService = inject(ConfigService);

  brandId = input.required<number>();
  configId = input.required<number>();
  configName = input.required<string>();
  selectedVersion = input<number | null>(null);
  activeVersion = input<number | undefined>(undefined);
  versions = input<Config[]>([]);

  versionSelected = output<number>();
  activeVersionSet = output<number>();
  notification = output<{ type: 'success' | 'error' | 'warning' | 'info'; message: string }>();

  isSettingActive = signal(false);
  isCollapsed = signal(true);
  previewVersion = signal<Config | null>(null);

  constructor() {
    // Set the first version as preview by default when versions change
    effect(() => {
      const versions = this.versions();
      this.previewVersion.set(versions.length > 0 ? versions[0] : null);
    });
  }

  toggleCollapse(): void {
    this.isCollapsed.update(v => !v);
  }

  onVersionChange(versionNumber: number): void {
    const version = this.versions().find(v => v.version === versionNumber);
    if (version) {
      this.previewVersion.set(version);
      this.versionSelected.emit(versionNumber);
    }
  }

  setActiveVersion(): void {
    const preview = this.previewVersion();
    if (!preview || this.isSettingActive()) return;

    this.isSettingActive.set(true);
    this.configService.setActiveVersion(this.brandId(), this.configName(), preview.version).subscribe({
      next: () => {
        this.activeVersionSet.emit(preview.version);
        this.notification.emit({ type: 'success', message: `Version ${preview.version} set as active` });
        this.isSettingActive.set(false);
      },
      error: () => {
        this.notification.emit({ type: 'error', message: 'Failed to set active version' });
        this.isSettingActive.set(false);
      }
    });
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }
}


@if (versions().length > 0) {
  <div class="version-selector" [class.collapsed]="isCollapsed()">
    <div class="version-selector__header" (click)="toggleCollapse()">
      <h3>Version History</h3>
      <div class="version-selector__header-right">
        <div class="version-selector__active-indicator">
          <span class="version-selector__active-label">Active Version:</span>
          <span class="version-selector__active-version">v{{ activeVersion() || 'Latest' }}</span>
        </div>
        <button class="version-selector__collapse-toggle" [attr.aria-label]="isCollapsed() ? 'Expand' : 'Collapse'">
          <mat-icon [style.transform]="isCollapsed() ? 'rotate(-90deg)' : 'rotate(0deg)'" [style.transition]="'transform 0.2s'">
            expand_more
          </mat-icon>
        </button>
      </div>
    </div>
    
    @if (!isCollapsed()) {
      <div class="version-selector__controls">
        <div class="version-selector__dropdown-container">
          <label for="version-select" class="version-selector__dropdown-label">
            Select Version to Preview:
          </label>
          <mat-form-field appearance="outline" class="version-selector__dropdown-field">
            <mat-select id="version-select" [value]="previewVersion()?.version || ''" (selectionChange)="onVersionChange($event.value)">
              @for (version of versions(); track version.id) {
                <mat-option [value]="version.version">
                  v{{ version.version }} - {{ formatDate(version.createdAt) }}
                  @if (activeVersion() === version.version) {
                    <span> (Active)</span>
                  }
                </mat-option>
              }
            </mat-select>
          </mat-form-field>
        </div>
        
        <div class="version-selector__actions">
          <button
            class="version-selector__set-active-btn"
            (click)="setActiveVersion()"
            [disabled]="isSettingActive() || (previewVersion() && activeVersion() === previewVersion()!.version)"
          >
            {{ isSettingActive() ? 'Setting...' : 'Set as Active Version' }}
          </button>
        </div>
      </div>
      
      @if (previewVersion()) {
        <div class="version-selector__preview">
          <div class="version-selector__preview-header">
            <h4>Preview - Version {{ previewVersion()!.version }}</h4>
            <div class="version-selector__preview-date">
              Created: {{ formatDate(previewVersion()!.createdAt) }}
            </div>
            @if (activeVersion() === previewVersion()!.version) {
              <div class="version-selector__preview-active-badge">Currently Active</div>
            }
          </div>
          
          @if (previewVersion()!.description) {
            <div class="version-selector__preview-description">
              <strong>Description:</strong> {{ previewVersion()!.description }}
            </div>
          }
          
          <div class="version-selector__preview-data">
            <strong>Form Data:</strong>
            <pre class="version-selector__preview-json">
              {{ previewVersion()!.formData | json }}
            </pre>
          </div>
        </div>
      }
    }
  </div>
}
