// apps/dinoconfig_builder/src/app/components/formElements/TextInputElement.tsx
import React from 'react';
import { BaseFormElementProps, FormElementWrapper } from './BaseFormElement';

interface TextInputElementProps extends BaseFormElementProps {
  onEdit?: () => void;
  onDelete?: () => void;
}

export default function TextInputElement({ 
  config, 
  value, 
  onChange, 
  onEdit, 
  onDelete,
  isEditable = true 
}: TextInputElementProps) {
  const inputType = config.type === 'text' ? 'text' :
                   config.type === 'email' ? 'email' :
                   config.type === 'password' ? 'password' :
                   config.type === 'url' ? 'url' :
                   config.type === 'tel' ? 'tel' :
                   config.type === 'search' ? 'search' :
                   config.type === 'time' ? 'time' :
                   config.type === 'datetime-local' ? 'datetime-local' :
                   config.type === 'month' ? 'month' :
                   config.type === 'week' ? 'week' :
                   'text';

  return (
    <FormElementWrapper config={config} onEdit={onEdit} onDelete={onDelete} isEditable={isEditable}>
      <input
        type={inputType}
        className="form-control"
        value={value || ''}
        onChange={(e) => onChange?.(e.target.value)}
        placeholder={`Enter ${config.label || config.name}`}
        required={config.required}
        maxLength={config.maxLength}
        pattern={config.pattern}
      />
    </FormElementWrapper>
  );
}

// apps/dinoconfig-builder/src/app/components/form-elements/text-input-element/text-input-element.component.ts
import { Component, input, output, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { FormsModule } from '@angular/forms';
import { GridFieldConfig } from '../../../models/config.models';
import { BaseFormElementComponent } from '../base-form-element/base-form-element.component';

@Component({
  selector: 'dc-text-input-element',
  standalone: true,
  imports: [CommonModule, MatFormFieldModule, MatInputModule, FormsModule, BaseFormElementComponent],
  templateUrl: './text-input-element.component.html',
  styleUrl: './text-input-element.component.scss'
})
export class TextInputElementComponent {
  config = input.required<GridFieldConfig>();
  value = input<any>();
  isEditable = input<boolean>(true);
  valueChange = output<any>();
  edit = output<void>();
  delete = output<void>();

  inputType = computed(() => {
    const typeMap: Record<string, string> = {
      'text': 'text',
      'email': 'email',
      'password': 'password',
      'url': 'url',
      'tel': 'tel',
      'search': 'search',
      'time': 'time',
      'datetime-local': 'datetime-local',
      'month': 'month',
      'week': 'week'
    };
    return typeMap[this.config().type] || 'text';
  });

  onValueChange(newValue: any): void {
    this.valueChange.emit(newValue);
  }
}


<dc-base-form-element
  [config]="config()"
  [isEditable]="isEditable()"
  (edit)="edit.emit()"
  (delete)="delete.emit()"
>
  <mat-form-field appearance="outline" class="w-full">
    <mat-label>{{ config().label || config().name }}</mat-label>
    <input
      matInput
      [type]="inputType()"
      [value]="value() || ''"
      (input)="onValueChange($any($event.target).value)"
      [placeholder]="'Enter ' + (config().label || config().name)"
      [required]="config().required"
      [attr.maxlength]="config().maxLength"
      [attr.pattern]="config().pattern"
    />
    @if (config().required) {
      <mat-hint class="required-hint">* Required</mat-hint>
    }
  </mat-form-field>
</dc-base-form-element>
