// apps/dinoconfig-builder/src/app/components/config-modal/config-modal.component.ts
import { Component, inject } from '@angular/core';

import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { MatDialogModule, MatDialogRef } from '@angular/material/dialog';

@Component({
  selector: 'dc-config-modal',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    MatDialogModule
],
  templateUrl: './config-modal.component.html',
  styleUrl: './config-modal.component.scss'
})
export class ConfigModalComponent {
  private fb = inject(FormBuilder);
  public dialogRef = inject(MatDialogRef<ConfigModalComponent>);

  configForm: FormGroup = this.fb.group({
    name: ['', [Validators.required]],
    description: ['']
  });

  onSubmit(): void {
    if (this.configForm.valid) {
      this.dialogRef.close(this.configForm.value);
    }
  }

  onCancel(): void {
    this.dialogRef.close();
  }
}


<div class="config-modal">
  <div class="dialog-header">
    <div class="header-gradient"></div>
    <div class="header-content">
      <div class="icon-wrapper">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
          <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </div>
      <div class="header-text">
        <h2 class="dialog-title">Create New Configuration</h2>
        <p class="dialog-subtitle">Add a new configuration to manage your settings</p>
      </div>
    </div>
  </div>

  <div class="dialog-content">
    <form [formGroup]="configForm" (ngSubmit)="onSubmit()" class="config-form">
      <div class="form-group">
        <label class="form-label">
          Configuration Name <span class="required">*</span>
        </label>
        <input
          type="text"
          class="form-input"
          formControlName="name"
          placeholder="Enter configuration name"
          [class.error]="configForm.get('name')?.hasError('required') && configForm.get('name')?.touched"
        />
        @if (configForm.get('name')?.hasError('required') && configForm.get('name')?.touched) {
          <span class="error-message">Configuration name is required</span>
        }
      </div>

      <div class="form-group">
        <label class="form-label">Description</label>
        <textarea
          class="form-textarea"
          formControlName="description"
          placeholder="Enter description (optional)"
          rows="3"
        ></textarea>
      </div>

      <div class="dialog-actions">
        <button
          type="button"
          class="btn btn-cancel"
          (click)="onCancel()"
        >
          Cancel
        </button>
        <button
          type="submit"
          class="btn btn-confirm"
          [disabled]="configForm.invalid"
        >
          Create
        </button>
      </div>
    </form>
  </div>
</div>

// apps/dinoconfig_builder/src/app/components/ConfigModal.tsx
import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import './ConfigModal.scss';

interface ConfigModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreate: (name: string, description?: string) => void;
  title?: string;
}

export default function ConfigModal({ isOpen, onClose, onCreate, title = "Create New Configuration" }: ConfigModalProps) {
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");

  useEffect(() => {
    if (isOpen) {
      // Reset form when modal opens
      setName("");
      setDescription("");
      // Prevent body scroll when modal is open
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'unset';
    }
    
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, [isOpen]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (name.trim()) {
      onCreate(name.trim(), description.trim() || undefined);
      onClose();
    }
  };

  const handleBackdropClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };

  if (!isOpen) return null;

  return createPortal(
    <div className="config-modal-backdrop" onClick={handleBackdropClick}>
      <div className="config-modal">
        <div className="modal-header">
          <h2>{title}</h2>
          <button className="close-btn" onClick={onClose} aria-label="Close">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
              <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
            </svg>
          </button>
        </div>

        <form onSubmit={handleSubmit} className="modal-body">
          <div className="form-group">
            <label htmlFor="config-name">Configuration Name *</label>
            <input
              id="config-name"
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g., Production Config, Development Settings"
              autoFocus
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="config-description">Description (optional)</label>
            <textarea
              id="config-description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Brief description of this configuration..."
              rows={3}
            />
          </div>

          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={onClose}>
              Cancel
            </button>
            <button type="submit" className="btn btn-primary" disabled={!name.trim()}>
              Create Configuration
            </button>
          </div>
        </form>
      </div>
    </div>,
    document.body
  );
}
