// apps/dinoconfig-builder/src/app/components/field-type-selector/field-type-selector.component.ts
import { Component, Input, Output, EventEmitter, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FieldType } from '../../models/config.models';

interface FieldTypeOption {
  value: FieldType;
  label: string;
  icon: string;
  description: string;
  category: 'text' | 'number' | 'choice' | 'date' | 'other';
}

@Component({
  selector: 'dc-field-type-selector',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './field-type-selector.component.html',
  styleUrl: './field-type-selector.component.scss'
})
export class FieldTypeSelectorComponent {
  @Input() value!: FieldType;
  @Output() valueChange = new EventEmitter<FieldType>();

  isOpen = signal(false);
  selectedCategory = signal<string>('text');

  fieldTypeOptions: FieldTypeOption[] = [
    { value: 'text', label: 'Text', icon: '📝', description: 'Single line text input', category: 'text' },
    { value: 'textarea', label: 'Text Area', icon: '📄', description: 'Multi-line text input', category: 'text' },
    { value: 'email', label: 'Email', icon: '📧', description: 'Email address input', category: 'text' },
    { value: 'password', label: 'Password', icon: '🔒', description: 'Password input field', category: 'text' },
    { value: 'url', label: 'URL', icon: '🔗', description: 'Web address input', category: 'text' },
    { value: 'tel', label: 'Phone', icon: '📞', description: 'Phone number input', category: 'text' },
    { value: 'search', label: 'Search', icon: '🔍', description: 'Search input field', category: 'text' },
    { value: 'number', label: 'Number', icon: '🔢', description: 'Numeric value input', category: 'number' },
    { value: 'range', label: 'Range', icon: '🎚️', description: 'Slider for number range', category: 'number' },
    { value: 'checkbox', label: 'Checkbox', icon: '☑️', description: 'True/false toggle', category: 'choice' },
    { value: 'select', label: 'Select', icon: '📋', description: 'Dropdown selection', category: 'choice' },
    { value: 'radio', label: 'Radio', icon: '🔘', description: 'Radio button group', category: 'choice' },
    { value: 'time', label: 'Time', icon: '🕐', description: 'Time picker', category: 'date' },
    { value: 'datetime-local', label: 'Date & Time', icon: '📅', description: 'Date and time picker', category: 'date' },
    { value: 'month', label: 'Month', icon: '📆', description: 'Month picker', category: 'date' },
    { value: 'week', label: 'Week', icon: '📊', description: 'Week picker', category: 'date' },
    { value: 'date', label: 'Date', icon: '📅', description: 'Date picker', category: 'date' },
  ];

  categories = [
    { id: 'text', label: 'Text Inputs', icon: '📝' },
    { id: 'number', label: 'Numbers', icon: '🔢' },
    { id: 'choice', label: 'Choices', icon: '☑️' },
    { id: 'date', label: 'Date & Time', icon: '📅' },
  ];

  get selectedOption(): FieldTypeOption | undefined {
    return this.fieldTypeOptions.find(opt => opt.value === this.value);
  }

  get filteredOptions(): FieldTypeOption[] {
    return this.fieldTypeOptions.filter(opt => opt.category === this.selectedCategory());
  }

  toggleOpen(): void {
    this.isOpen.set(!this.isOpen());
  }

  selectCategory(categoryId: string): void {
    this.selectedCategory.set(categoryId);
  }

  selectType(type: FieldType): void {
    this.valueChange.emit(type);
    this.isOpen.set(false);
  }
}


<div class="field-type-selector-expanded">
  <button 
    type="button"
    class="type-selector-toggle"
    (click)="toggleOpen()"
  >
    <svg 
      [class.open]="isOpen()"
      class="chevron"
      width="16" 
      height="16" 
      viewBox="0 0 16 16" 
      fill="none"
    >
      <path d="M4 6L8 10L12 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    Field Type: {{ selectedOption?.icon }} {{ selectedOption?.label }}
    {{ isOpen() ? ' (Hide)' : ' (Show)' }}
  </button>

  @if (isOpen()) {
    <div class="type-selector-panel">
      <div class="category-tabs">
        @for (cat of categories; track cat.id) {
          <button
            type="button"
            [class.active]="selectedCategory() === cat.id"
            class="category-tab"
            (click)="selectCategory(cat.id)"
          >
            <span class="cat-icon">{{ cat.icon }}</span>
            <span class="cat-label">{{ cat.label }}</span>
          </button>
        }
      </div>

      <div class="type-options-grid">
        @for (option of filteredOptions; track option.value) {
          <button
            type="button"
            [class.selected]="value === option.value"
            class="type-option"
            (click)="selectType(option.value)"
          >
            <span class="option-icon">{{ option.icon }}</span>
            <div class="option-content">
              <span class="option-label">{{ option.label }}</span>
              <span class="option-description">{{ option.description }}</span>
            </div>
            @if (value === option.value) {
              <svg class="check-icon" width="20" height="20" viewBox="0 0 20 20" fill="none">
                <path d="M16.667 5L7.5 14.167L3.333 10" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            }
          </button>
        }
      </div>
    </div>
  }
</div>

// apps/dinoconfig_builder/src/app/components/FieldTypeSelector.tsx
import React from 'react';
import { FieldType } from '../types';
import './FieldTypeSelector.scss';

interface FieldTypeOption {
  value: FieldType;
  label: string;
  icon: string;
  description: string;
  category: 'text' | 'number' | 'choice' | 'date' | 'other';
}

const fieldTypeOptions: FieldTypeOption[] = [
  { value: 'text', label: 'Text', icon: '📝', description: 'Single line text input', category: 'text' },
  { value: 'textarea', label: 'Text Area', icon: '📄', description: 'Multi-line text input', category: 'text' },
  { value: 'email', label: 'Email', icon: '📧', description: 'Email address input', category: 'text' },
  { value: 'password', label: 'Password', icon: '🔒', description: 'Password input field', category: 'text' },
  { value: 'url', label: 'URL', icon: '🔗', description: 'Web address input', category: 'text' },
  { value: 'tel', label: 'Phone', icon: '📞', description: 'Phone number input', category: 'text' },
  { value: 'search', label: 'Search', icon: '🔍', description: 'Search input field', category: 'text' },
  
  { value: 'number', label: 'Number', icon: '🔢', description: 'Numeric value input', category: 'number' },
  { value: 'range', label: 'Range', icon: '🎚️', description: 'Slider for number range', category: 'number' },
  
  { value: 'checkbox', label: 'Checkbox', icon: '☑️', description: 'True/false toggle', category: 'choice' },
  { value: 'select', label: 'Select', icon: '📋', description: 'Dropdown selection', category: 'choice' },
  { value: 'radio', label: 'Radio', icon: '🔘', description: 'Radio button group', category: 'choice' },
  
  { value: 'time', label: 'Time', icon: '🕐', description: 'Time picker', category: 'date' },
  { value: 'datetime-local', label: 'Date & Time', icon: '📅', description: 'Date and time picker', category: 'date' },
  { value: 'month', label: 'Month', icon: '📆', description: 'Month picker', category: 'date' },
  { value: 'week', label: 'Week', icon: '📊', description: 'Week picker', category: 'date' },
];

const categories = [
  { id: 'text', label: 'Text Inputs', icon: '📝' },
  { id: 'number', label: 'Numbers', icon: '🔢' },
  { id: 'choice', label: 'Choices', icon: '☑️' },
  { id: 'date', label: 'Date & Time', icon: '📅' },
];

interface FieldTypeSelectorProps {
  value: FieldType;
  onChange: (type: FieldType) => void;
}

export default function FieldTypeSelector({ value, onChange }: FieldTypeSelectorProps) {
  const [isOpen, setIsOpen] = React.useState(false);
  const [selectedCategory, setSelectedCategory] = React.useState<string>('text');

  const selectedOption = fieldTypeOptions.find(opt => opt.value === value);
  const filteredOptions = fieldTypeOptions.filter(opt => opt.category === selectedCategory);

  const handleSelect = (type: FieldType) => {
    onChange(type);
    setIsOpen(false);
  };

  return (
    <div className="field-type-selector-expanded">
      <button 
        type="button"
        className="type-selector-toggle"
        onClick={() => setIsOpen(!isOpen)}
      >
        <svg 
          className={`chevron ${isOpen ? 'open' : ''}`}
          width="16" 
          height="16" 
          viewBox="0 0 16 16" 
          fill="none"
        >
          <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
        Field Type: {selectedOption?.icon} {selectedOption?.label}
        {isOpen ? ' (Hide)' : ' (Show)'}
      </button>

      {isOpen && (
        <div className="type-selector-panel">
          <div className="category-tabs">
            {categories.map(cat => (
              <button
                key={cat.id}
                type="button"
                className={`category-tab ${selectedCategory === cat.id ? 'active' : ''}`}
                onClick={() => setSelectedCategory(cat.id)}
              >
                <span className="cat-icon">{cat.icon}</span>
                <span className="cat-label">{cat.label}</span>
              </button>
            ))}
          </div>

          <div className="type-options-grid">
            {filteredOptions.map(option => (
              <button
                key={option.value}
                type="button"
                className={`type-option ${value === option.value ? 'selected' : ''}`}
                onClick={() => handleSelect(option.value)}
              >
                <span className="option-icon">{option.icon}</span>
                <div className="option-content">
                  <span className="option-label">{option.label}</span>
                  <span className="option-description">{option.description}</span>
                </div>
                {value === option.value && (
                  <svg className="check-icon" width="20" height="20" viewBox="0 0 20 20" fill="none">
                    <path d="M16.667 5L7.5 14.167L3.333 10" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                )}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
