// apps/dinoconfig-builder/src/app/components/field-form/field-form.component.ts
import { Component, input, output, signal, computed, effect, ChangeDetectionStrategy, inject } from '@angular/core';

import { FormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { FieldConfig, FieldType } from '../../models/config.models';
import { FieldTypeSelectorComponent } from '../field-type-selector/field-type-selector.component';
import { FieldUtilsService } from '../../services/field-utils.service';

export type FieldFormMode = 'add' | 'edit';

@Component({
  selector: 'dc-field-form',
  standalone: true,
  imports: [
    FormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatCheckboxModule,
    MatButtonModule,
    MatIconModule,
    FieldTypeSelectorComponent
],
  templateUrl: './field-form.component.html',
  styleUrl: './field-form.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FieldFormComponent {
  // Signal-based inputs
  mode = input<FieldFormMode>('add');
  field = input.required<FieldConfig>();
  
  // Signal-based outputs
  save = output<FieldConfig>();
  cancel = output<void>();

  private fieldUtils = inject(FieldUtilsService);

  showValidations = signal(false);
  isSaving = signal(false);
  
  fieldData = signal<FieldConfig>({
    name: '',
    type: 'text',
    label: '',
    options: '',
    required: false
  });

  isChoiceField = computed(() => this.fieldUtils.isChoiceType(this.fieldData().type));
  isNumberField = computed(() => this.fieldUtils.isNumberType(this.fieldData().type));
  isTextLikeField = computed(() => this.fieldUtils.isTextType(this.fieldData().type));
  isValid = computed(() => !!this.fieldData().name?.trim());

  constructor() {
    // Effect to sync field input with fieldData signal
    effect(() => {
      const fieldValue = this.field();
      if (fieldValue) {
        this.fieldData.set({ ...fieldValue });
      }
    });
  }

  updateField(key: keyof FieldConfig, value: any): void {
    this.fieldData.update(prev => ({
      ...prev,
      [key]: value
    }));
  }

  onTypeChange(type: FieldType): void {
    this.updateField('type', type);
  }

  toggleValidations(): void {
    this.showValidations.update(v => !v);
  }

  onSave(): void {
    if (!this.isValid()) return;
    
    this.isSaving.set(true);
    this.save.emit({ ...this.fieldData() });
    this.isSaving.set(false);
  }

  onCancel(): void {
    this.cancel.emit();
  }

  parseNumber(value: string): number | undefined {
    return value ? Number(value) : undefined;
  }
}


<div class="field-builder-form">
  <div class="form-row">
    <div class="form-group">
      <label [for]="mode + '-field-name'">
        Field Name *
        <span class="label-hint">The unique identifier for this field</span>
      </label>
      <input
        [id]="mode + '-field-name'"
        placeholder="e.g., username, apiKey, maxRetries"
        [value]="fieldData().name || ''"
        (input)="updateField('name', $any($event.target).value)"
      />
    </div>
    <div class="form-group">
      <label [for]="mode + '-field-label'">
        Display Label
        <span class="label-hint">Optional label shown to users</span>
      </label>
      <input
        [id]="mode + '-field-label'"
        placeholder="e.g., Username, API Key, Max Retries"
        [value]="fieldData().label || ''"
        (input)="updateField('label', $any($event.target).value)"
      />
    </div>
  </div>

  <dc-field-type-selector
    [value]="fieldData().type"
    (valueChange)="onTypeChange($event)"
  ></dc-field-type-selector>

  @if (isChoiceField()) {
    <div class="form-group options-group">
      <label [for]="mode + '-field-options'">
        Options *
        <span class="label-hint">Comma-separated list of choices</span>
      </label>
      <input
        [id]="mode + '-field-options'"
        placeholder="e.g., Option 1, Option 2, Option 3"
        [value]="fieldData().options || ''"
        (input)="updateField('options', $any($event.target).value)"
      />
    </div>
  }

  <div class="validation-section">
    <button
      type="button"
      class="validation-toggle"
      (click)="toggleValidations()"
    >
      <svg [class.open]="showValidations()" class="chevron" width="16" height="16" viewBox="0 0 16 16" fill="none">
        <path d="M4 6L8 10L12 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </svg>
      Advanced Validation Settings
      {{ showValidations() ? ' (Hide)' : ' (Show)' }}
    </button>

    @if (showValidations()) {
      <div class="validation-fields">
        <label class="checkbox-label">
          <input
            type="checkbox"
            [checked]="fieldData().required || false"
            (change)="updateField('required', $any($event.target).checked)"
          />
          <span>Required field</span>
        </label>

        @if (isNumberField()) {
          <div class="form-row">
            <div class="form-group">
              <label [for]="mode + '-field-min'">Minimum Value</label>
              <input
                [id]="mode + '-field-min'"
                type="number"
                placeholder="Min"
                [value]="fieldData().min ?? ''"
                (input)="updateField('min', parseNumber($any($event.target).value))"
              />
            </div>
            <div class="form-group">
              <label [for]="mode + '-field-max'">Maximum Value</label>
              <input
                [id]="mode + '-field-max'"
                type="number"
                placeholder="Max"
                [value]="fieldData().max ?? ''"
                (input)="updateField('max', parseNumber($any($event.target).value))"
              />
            </div>
          </div>
        }

        @if (isTextLikeField()) {
          <div class="form-group">
            <label [for]="mode + '-field-maxlength'">Maximum Length</label>
            <input
              [id]="mode + '-field-maxlength'"
              type="number"
              placeholder="Maximum character length"
              [value]="fieldData().maxLength ?? ''"
              (input)="updateField('maxLength', parseNumber($any($event.target).value))"
            />
          </div>
          <div class="form-group">
            <label [for]="mode + '-field-pattern'">Pattern (Regular Expression)</label>
            <input
              [id]="mode + '-field-pattern'"
              placeholder="e.g., ^[a-zA-Z0-9]*$"
              [value]="fieldData().pattern || ''"
              (input)="updateField('pattern', $any($event.target).value || undefined)"
            />
          </div>
        }
      </div>
    }
  </div>

  <div class="form-actions">
    <button
      class="btn btn-primary"
      (click)="onSave()"
      [disabled]="!isValid() || isSaving()"
    >
      @if (mode() === 'edit') {
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
          <path d="M13.333 4L6 11.333 2.667 8" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
      } @else {
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
          <path d="M8 3.333v9.334M3.333 8h9.334" stroke="currentColor" stroke-width="2" stroke-linecap="round" />
        </svg>
      }
      {{ mode() === 'edit' ? 'Save Field Changes' : 'Add Field' }}
    </button>
    <button class="btn btn-ghost" (click)="onCancel()" [disabled]="isSaving()">
      {{ mode() === 'edit' ? 'Cancel Editing' : 'Cancel' }}
    </button>
  </div>
</div>

// apps/dinoconfig_builder/src/app/components/FieldForm.tsx
import React, { ChangeEvent } from 'react';
import { FieldConfig, FieldType } from '../types';
import FieldTypeSelector from './FieldTypeSelector';

export type FieldFormMode = 'add' | 'edit';

interface FieldFormProps {
  mode: FieldFormMode;
  field: FieldConfig;
  setField: React.Dispatch<React.SetStateAction<FieldConfig>>;
  showValidations: boolean;
  setShowValidations: React.Dispatch<React.SetStateAction<boolean>>;
  onSave: () => Promise<void> | void;
  onCancel: () => void;
  isSaving: boolean;
}

const FieldFormView: React.FC<FieldFormProps> = ({
  mode,
  field,
  setField,
  showValidations,
  setShowValidations,
  onSave,
  onCancel,
  isSaving,
}) => {
  const handleFieldChange = (key: keyof FieldConfig) => (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const value =
      event.target.type === 'checkbox' ? (event.target as HTMLInputElement).checked : event.target.value;
    setField(prev => ({
      ...prev,
      [key]: value as any,
    }));
  };

  const handleTypeChange = (type: FieldType) => {
    setField(prev => ({
      ...prev,
      type,
    }));
  };

  const handleSaveClick = async (event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    await onSave();
  };

  const handleCancelClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    onCancel();
  };

  const isChoiceField = field.type === 'select' || field.type === 'radio';
  const isNumberField = field.type === 'number' || field.type === 'range';
  const isTextLikeField = [
    'text',
    'textarea',
    'email',
    'search',
    'url',
    'tel',
    'time',
    'datetime',
    'datetime-local',
    'month',
    'week',
  ].includes(field.type);

  const primaryLabel = mode === 'edit' ? 'Save Field Changes' : 'Add Field';
  const secondaryLabel = mode === 'edit' ? 'Cancel Editing' : 'Cancel';

  return (
    <div className="field-builder-form">
      <div className="form-row">
        <div className="form-group">
          <label htmlFor={`${mode}-field-name`}>
            Field Name *
            <span className="label-hint">The unique identifier for this field</span>
          </label>
          <input
            id={`${mode}-field-name`}
            placeholder="e.g., username, apiKey, maxRetries"
            value={field.name}
            onChange={handleFieldChange('name')}
          />
        </div>
        <div className="form-group">
          <label htmlFor={`${mode}-field-label`}>
            Display Label
            <span className="label-hint">Optional label shown to users</span>
          </label>
          <input
            id={`${mode}-field-label`}
            placeholder="e.g., Username, API Key, Max Retries"
            value={field.label}
            onChange={handleFieldChange('label')}
          />
        </div>
      </div>

      <FieldTypeSelector value={field.type} onChange={handleTypeChange} />

      {isChoiceField && (
        <div className="form-group options-group">
          <label htmlFor={`${mode}-field-options`}>
            Options *
            <span className="label-hint">Comma-separated list of choices</span>
          </label>
          <input
            id={`${mode}-field-options`}
            placeholder="e.g., Option 1, Option 2, Option 3"
            value={field.options}
            onChange={handleFieldChange('options')}
          />
        </div>
      )}

      <div className="validation-section">
        <button
          type="button"
          className="validation-toggle"
          onClick={() => setShowValidations(open => !open)}
        >
          <svg className={`chevron ${showValidations ? 'open' : ''}`} width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          Advanced Validation Settings
          {showValidations ? ' (Hide)' : ' (Show)'}
        </button>

        {showValidations && (
          <div className="validation-fields">
            <label className="checkbox-label">
              <input
                type="checkbox"
                checked={!!field.required}
                onChange={event =>
                  setField(prev => ({
                    ...prev,
                    required: event.target.checked,
                  }))
                }
              />
              <span>Required field</span>
            </label>

            {isNumberField && (
              <div className="form-row">
                <div className="form-group">
                  <label htmlFor={`${mode}-field-min`}>Minimum Value</label>
                  <input
                    id={`${mode}-field-min`}
                    type="number"
                    placeholder="Min"
                    value={field.min ?? ''}
                    onChange={event =>
                      setField(prev => ({
                        ...prev,
                        min: event.target.value ? Number(event.target.value) : undefined,
                      }))
                    }
                  />
                </div>
                <div className="form-group">
                  <label htmlFor={`${mode}-field-max`}>Maximum Value</label>
                  <input
                    id={`${mode}-field-max`}
                    type="number"
                    placeholder="Max"
                    value={field.max ?? ''}
                    onChange={event =>
                      setField(prev => ({
                        ...prev,
                        max: event.target.value ? Number(event.target.value) : undefined,
                      }))
                    }
                  />
                </div>
              </div>
            )}

            {isTextLikeField && (
              <>
                <div className="form-group">
                  <label htmlFor={`${mode}-field-maxlength`}>Maximum Length</label>
                  <input
                    id={`${mode}-field-maxlength`}
                    type="number"
                    placeholder="Maximum character length"
                    value={field.maxLength ?? ''}
                    onChange={event =>
                      setField(prev => ({
                        ...prev,
                        maxLength: event.target.value ? Number(event.target.value) : undefined,
                      }))
                    }
                  />
                </div>
                <div className="form-group">
                  <label htmlFor={`${mode}-field-pattern`}>Pattern (Regular Expression)</label>
                  <input
                    id={`${mode}-field-pattern`}
                    placeholder="e.g., ^[a-zA-Z0-9]*$"
                    value={field.pattern ?? ''}
                    onChange={event =>
                      setField(prev => ({
                        ...prev,
                        pattern: event.target.value || undefined,
                      }))
                    }
                  />
                </div>
              </>
            )}
          </div>
        )}
      </div>

      <div className="form-actions">
        <button
          className="btn btn-primary"
          onClick={handleSaveClick}
          disabled={!field.name.trim() || isSaving}
        >
          {mode === 'edit' ? (
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path d="M13.333 4L6 11.333 2.667 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          ) : (
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path d="M8 3.333v9.334M3.333 8h9.334" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
            </svg>
          )}
          {primaryLabel}
        </button>
        <button className="btn btn-ghost" onClick={handleCancelClick} disabled={isSaving}>
          {secondaryLabel}
        </button>
      </div>
    </div>
  );
};

export default FieldFormView;
