// apps/dinoconfig-builder/src/app/components/shared/idle-warning-modal/idle-warning-modal.component.ts
import { Component, input, output, signal, effect, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'dc-idle-warning-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './idle-warning-modal.component.html',
  styleUrl: './idle-warning-modal.component.scss'
})
export class IdleWarningModalComponent {
  isVisible = input.required<boolean>();
  remainingSeconds = input.required<number>();
  onKeepSession = output<void>();
  onLogout = output<void>();

  countdown = signal<number>(0);
  minutes = computed(() => Math.floor(this.countdown() / 60));
  seconds = computed(() => this.countdown() % 60);

  private countdownInterval: ReturnType<typeof setInterval> | null = null;

  constructor() {
    effect(() => {
      const remaining = this.remainingSeconds();
      this.countdown.set(remaining);
    });

    effect(() => {
      const visible = this.isVisible();
      const countdown = this.countdown();

      if (visible && countdown > 0) {
        this.startCountdown();
      } else {
        this.stopCountdown();
      }
    });
  }

  private startCountdown(): void {
    this.stopCountdown();
    
    this.countdownInterval = setInterval(() => {
      this.countdown.update(value => {
        if (value <= 1) {
          this.stopCountdown();
          return 0;
        }
        return value - 1;
      });
    }, 1000);
  }

  private stopCountdown(): void {
    if (this.countdownInterval) {
      clearInterval(this.countdownInterval);
      this.countdownInterval = null;
    }
  }
}


@if (isVisible()) {
  <div class="idle-warning-overlay">
    <div class="idle-warning-modal">
      <div class="idle-warning-icon">
        <svg width="64" height="64" viewBox="0 0 64 64" fill="none">
          <circle cx="32" cy="32" r="30" stroke="#f59e0b" stroke-width="4" fill="#fef3c7"/>
          <path d="M32 20v16M32 44h.02" stroke="#f59e0b" stroke-width="4" stroke-linecap="round"/>
        </svg>
      </div>

      <h2 class="idle-warning-title">Session Expiring Soon</h2>
      
      <p class="idle-warning-message">
        You've been inactive for a while. Your session will expire in:
      </p>

      <div class="idle-warning-countdown">
        <span class="countdown-time">
          {{ minutes() }}:{{ seconds().toString().padStart(2, '0') }}
        </span>
      </div>

      <p class="idle-warning-submessage">
        Click "Keep Session" to continue working, or you'll be logged out automatically.
      </p>

      <div class="idle-warning-actions">
        <button 
          class="btn btn--primary btn--large"
          (click)="onKeepSession.emit()"
        >
          <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
            <path d="M16.667 9.167v5a1.667 1.667 0 01-1.667 1.666H5a1.667 1.667 0 01-1.667-1.666v-10A1.667 1.667 0 015 2.5h5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M13.333 2.5h5v5M8.333 11.667L18.333 2.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          Keep Session Active
        </button>
        
        <button 
          class="btn btn--outline btn--large"
          (mousedown)="$event.stopPropagation()"
          (touchstart)="$event.stopPropagation()"
          (click)="$event.stopPropagation(); onLogout.emit()"
        >
          Logout Now
        </button>
      </div>

      <div class="idle-warning-info">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
          <circle cx="8" cy="8" r="7" stroke="currentColor" stroke-width="1.5"/>
          <path d="M8 7v4M8 5h.01" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
        </svg>
        <span>Any activity will automatically extend your session</span>
      </div>
    </div>
  </div>
}

// apps/dinoconfig_builder/src/app/components/idle-warning-modal.tsx
import React, { useEffect, useState } from 'react';
import './idle-warning-modal.scss';

interface IdleWarningModalProps {
  isVisible: boolean;
  remainingSeconds: number;
  onKeepSession: () => void;
  onLogout: () => void;
}

export const IdleWarningModal: React.FC<IdleWarningModalProps> = ({
  isVisible,
  remainingSeconds,
  onKeepSession,
  onLogout
}) => {
  const [countdown, setCountdown] = useState(remainingSeconds);

  useEffect(() => {
    setCountdown(remainingSeconds);
  }, [remainingSeconds]);

  useEffect(() => {
    if (!isVisible) return;

    const interval = setInterval(() => {
      setCountdown(prev => {
        if (prev <= 1) {
          clearInterval(interval);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(interval);
  }, [isVisible]);

  if (!isVisible) return null;

  const minutes = Math.floor(countdown / 60);
  const seconds = countdown % 60;

  return (
    <div className="idle-warning-overlay">
      <div className="idle-warning-modal">
        <div className="idle-warning-icon">
          <svg width="64" height="64" viewBox="0 0 64 64" fill="none">
            <circle cx="32" cy="32" r="30" stroke="#f59e0b" strokeWidth="4" fill="#fef3c7"/>
            <path d="M32 20v16M32 44h.02" stroke="#f59e0b" strokeWidth="4" strokeLinecap="round"/>
          </svg>
        </div>

        <h2 className="idle-warning-title">Session Expiring Soon</h2>
        
        <p className="idle-warning-message">
          You've been inactive for a while. Your session will expire in:
        </p>

        <div className="idle-warning-countdown">
          <span className="countdown-time">
            {minutes}:{seconds.toString().padStart(2, '0')}
          </span>
        </div>

        <p className="idle-warning-submessage">
          Click "Keep Session" to continue working, or you'll be logged out automatically.
        </p>

        <div className="idle-warning-actions">
          <button 
            className="btn btn--primary btn--large"
            onClick={onKeepSession}
          >
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path d="M16.667 9.167v5a1.667 1.667 0 01-1.667 1.666H5a1.667 1.667 0 01-1.667-1.666v-10A1.667 1.667 0 015 2.5h5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M13.333 2.5h5v5M8.333 11.667L18.333 2.5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
            Keep Session Active
          </button>
          
          <button 
            className="btn btn--outline btn--large"
            onClick={onLogout}
          >
            Logout Now
          </button>
        </div>

        <div className="idle-warning-info">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <circle cx="8" cy="8" r="7" stroke="currentColor" strokeWidth="1.5"/>
            <path d="M8 7v4M8 5h.01" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
          </svg>
          <span>Any activity will automatically extend your session</span>
        </div>
      </div>
    </div>
  );
};
