// apps/dinoconfig_builder/src/app/pages/subscription-cancel.tsx
import React from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { subscriptionService } from '../services/subscription.service';
import { useSubscription } from '../auth/subscription-context';
import './subscription-cancel.scss';

export const SubscriptionCancel: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { subscription, loading } = useSubscription();

  const getCurrentTierName = () => {
    if (!subscription) return 'Free';
    return subscriptionService.getTierDisplayName(subscription.tier);
  };

  const getCurrentTierDescription = () => {
    if (!subscription) return '1 brand, 1 config per brand';
    return subscriptionService.getTierDescription(subscription.tier);
  };

  return (
    <div className="subscription-cancel">
      <div className="subscription-cancel__card">
        <div className="subscription-cancel__icon">✗</div>
        <h1>Checkout Cancelled</h1>
        <p>Your subscription upgrade was cancelled.</p>
        <p>No charges were made to your account.</p>
        
        {!loading && subscription && (
          <div className="subscription-cancel__current-plan">
            <h3>Your current plan:</h3>
            <div className="subscription-cancel__plan-info">
              <span className="subscription-cancel__plan-name">{getCurrentTierName()}</span>
              <span className="subscription-cancel__plan-description">{getCurrentTierDescription()}</span>
            </div>
          </div>
        )}

        <div className="subscription-cancel__help">
          <h4>Need help?</h4>
          <p>If you encountered any issues during checkout, please:</p>
          <ul>
            <li>Check your payment method details</li>
            <li>Ensure you have sufficient funds</li>
            <li>Contact support if the problem persists</li>
          </ul>
        </div>

        <div className="subscription-cancel__actions">
          <button 
            className="subscription-cancel__button subscription-cancel__button--primary"
            onClick={() => navigate('/subscription')}
          >
            Try Again
          </button>
          <button 
            className="subscription-cancel__button subscription-cancel__button--secondary"
            onClick={() => navigate('/')}
          >
            Return Home
          </button>
          <button 
            className="subscription-cancel__button subscription-cancel__button--link"
            onClick={() => window.open('mailto:support@dinoconfig.com?subject=Checkout%20Issue', '_blank')}
          >
            Contact Support
          </button>
        </div>
      </div>
    </div>
  );
};

// apps/dinoconfig-builder/src/app/components/subscription-cancel/subscription-cancel.component.ts
import { Component, signal, inject, OnInit } from '@angular/core';

import { Router, ActivatedRoute } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { SubscriptionService } from '../../services/subscription.service';
import { SubscriptionStatus } from '../../models/subscription.models';
import { catchError, of } from 'rxjs';

@Component({
  selector: 'dc-subscription-cancel',
  standalone: true,
  imports: [
    MatButtonModule
],
  templateUrl: './subscription-cancel.component.html',
  styleUrl: './subscription-cancel.component.scss'
})
export class SubscriptionCancelComponent implements OnInit {
  private router = inject(Router);
  private route = inject(ActivatedRoute);
  private subscriptionService = inject(SubscriptionService);

  subscription = signal<SubscriptionStatus | null>(null);
  loading = signal<boolean>(true);

  ngOnInit(): void {
    this.loadSubscription();
  }

  loadSubscription(): void {
    this.loading.set(true);
    this.subscriptionService.getSubscriptionWithViolations().pipe(
      catchError(() => of(null))
    ).subscribe(data => {
      if (data) {
        this.subscription.set({
          tier: data.tier,
          status: data.status,
          limits: data.limits,
          features: data.features,
          currentPeriodEnd: data.currentPeriodEnd,
          isActive: data.isActive
        });
      }
      this.loading.set(false);
    });
  }

  getCurrentTierName(): string {
    if (!this.subscription()) return 'Free';
    return this.subscriptionService.getTierDisplayName(this.subscription()!.tier);
  }

  getCurrentTierDescription(): string {
    if (!this.subscription()) return '1 brand, 1 config per brand';
    const tier = this.subscription()!.tier;
    switch (tier) {
      case 'free':
        return '1 brand, 1 config per brand';
      case 'starter':
        return '5 brands, 3 configs per brand';
      case 'pro':
        return '20 brands, 20 configs per brand';
      case 'custom':
        return 'Unlimited brands and configs';
      default:
        return '';
    }
  }

  goToSubscription(): void {
    this.router.navigate(['/subscription']);
  }

  goHome(): void {
    this.router.navigate(['/']);
  }

  contactSupport(): void {
    window.open('mailto:support@dinoconfig.com?subject=Checkout%20Issue', '_blank');
  }
}


<div class="subscription-cancel">
  <div class="subscription-cancel__card">
    <div class="subscription-cancel__icon">✗</div>
    <h1>Checkout Cancelled</h1>
    <p>Your subscription upgrade was cancelled.</p>
    <p>No charges were made to your account.</p>
    
    @if (!loading() && subscription()) {
      <div class="subscription-cancel__current-plan">
        <h3>Your current plan:</h3>
        <div class="subscription-cancel__plan-info">
          <span class="subscription-cancel__plan-name">{{ getCurrentTierName() }}</span>
          <span class="subscription-cancel__plan-description">{{ getCurrentTierDescription() }}</span>
        </div>
      </div>
    }

    <div class="subscription-cancel__help">
      <h4>Need help?</h4>
      <p>If you encountered any issues during checkout, please:</p>
      <ul>
        <li>Check your payment method details</li>
        <li>Ensure you have sufficient funds</li>
        <li>Contact support if the problem persists</li>
      </ul>
    </div>

    <div class="subscription-cancel__actions">
      <button 
        class="subscription-cancel__button subscription-cancel__button--primary"
        (click)="goToSubscription()">
        Try Again
      </button>
      <button 
        class="subscription-cancel__button subscription-cancel__button--secondary"
        (click)="goHome()">
        Return Home
      </button>
      <button 
        class="subscription-cancel__button subscription-cancel__button--link"
        (click)="contactSupport()">
        Contact Support
      </button>
    </div>
  </div>
</div>
