// apps/dinoconfig_builder/src/app/components/BrandHeader.tsx
import React from 'react';
import { Brand } from '../types';
import './BrandHeader.scss';
import { IoChevronBack } from 'react-icons/io5';
import { useNavigate } from 'react-router-dom';

interface BrandHeaderProps {
  brand: Brand | null;
}

export default function BrandHeader({ brand }: BrandHeaderProps) {
  const navigate = useNavigate();

  if (!brand) {
    navigate('/brands')
  }

  return (
    <div className="brand-header">
      <button className="btn back-button" onClick={() => navigate('/brands') }>
        <IoChevronBack />
        {/* <span>Back to Brands</span> */}
      </button>
      <div className="brand-info">
        <div className="brand-field">
          <span className="field-label">Brand name:</span>
          <h1 className="field-value">{brand?.name}</h1>
        </div>
        {brand?.description && (
          <div className="brand-field">
            <span className="field-label">Description:</span>
            <p className="field-value">{brand?.description}</p>
          </div>
        )}
      </div>
    </div>
  );
}

// apps/dinoconfig-builder/src/app/components/brand-header/brand-header.component.ts
import { Component, input, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { Brand } from '../../models/user.models';

@Component({
  selector: 'dc-brand-header',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule],
  templateUrl: './brand-header.component.html',
  styleUrl: './brand-header.component.scss'
})
export class BrandHeaderComponent {
  private router = inject(Router);

  brand = input<Brand | null>(null);

  goBack(): void {
    this.router.navigate(['/brands']);
  }
}


<div class="brand-header">
  <button class="btn back-button" (click)="goBack()">
    <mat-icon>chevron_left</mat-icon>
  </button>
  <div class="brand-info">
    @if (brand()) {
      <div class="brand-field">
        <span class="field-label">Brand name:</span>
        <div class="field-value">
          <h1>{{ brand()!.name }}</h1>
        </div>
      </div>
      @if (brand()!.description) {
        <div class="brand-field">
          <span class="field-label">Description:</span>
          <div class="field-value">
            <p>{{ brand()!.description }}</p>
          </div>
        </div>
      }
    }
  </div>
</div>
