// apps/dinoconfig_builder/src/app/pages/Profile.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Spinner } from '../components';
import { useUser } from '../auth/user-context';
import { subscriptionService, SubscriptionStatus } from '../services/subscription.service';
import './Profile.scss';

export default function Profile() {
    const navigate = useNavigate();
    const { user, loading, refreshUser } = useUser();
    const [error, setError] = useState<string | null>(null);
    const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['personal', 'address', 'account', 'subscription', 'brands']));
    const [subscription, setSubscription] = useState<SubscriptionStatus | null>(null);
    const [loadingSubscription, setLoadingSubscription] = useState(true);

    useEffect(() => {
      loadSubscription();
    }, []);

    const loadSubscription = async () => {
      try {
        const status = await subscriptionService.getSubscriptionStatus();
        setSubscription(status);
      } catch (err) {
        console.error('Failed to load subscription:', err);
      } finally {
        setLoadingSubscription(false);
      }
    };

    const toggleSection = (section: string) => {
      const newExpanded = new Set(expandedSections);
      if (newExpanded.has(section)) {
        newExpanded.delete(section);
      } else {
        newExpanded.add(section);
      }
      setExpandedSections(newExpanded);
    };
  
  if (loading) {
    return (
      <div className="profile-page">
        <Spinner text="Loading profile..." size="large" fullHeight />
      </div>
    );
  }

  if (error) {
    return (
      <div className="profile-page">
        <div className="error-state">
          <h2>Error loading profile</h2>
          <p>{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="profile-page">
      <div className="main-layout">
        <div className="profile-header">
          <div className="header-content">
            <h1 className="page-title">User Profile</h1>
            <p className="page-subtitle">View and manage your account information</p>
          </div>
          <button 
            className="btn btn-outline refresh-btn" 
            onClick={refreshUser}
            disabled={loading}
          >
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path d="M14 8A6 6 0 1 1 2 8a6 6 0 0 1 12 0Z" stroke="currentColor" strokeWidth="1.5"/>
              <path d="M8 4v4l2 2" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
            </svg>
            {loading ? 'Refreshing...' : 'Refresh Profile'}
          </button>
        </div>

        <div className="main-content">
          <div className="profile-container">
            <div className="profile-content">
              
              <div className="profile-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('personal')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('personal') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  {/* <span className="section-icon">👤</span> */}
                  <span className="section-title">Personal Information</span>
                </button>
                
                {expandedSections.has('personal') && (
                <div className="profile-grid">
                  <div className="profile-field">
                    <span className="field-label">First Name:</span>
                    <span className="field-value">{user?.firstName}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">Last Name:</span>
                    <span className="field-value">{user?.lastName}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">Email:</span>
                    <span className="field-value">{user?.email}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">Phone Number:</span>
                    <span className="field-value">{user?.phoneNumber || 'Not provided'}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">Company Name:</span>
                    <span className="field-value">{user?.companyName || 'Not provided'}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">Account Status:</span>
                    <span className={`field-value status ${user?.isActive ? 'active' : 'inactive'}`}>
                      {user?.isActive ? 'Active' : 'Inactive'}
                    </span>
                  </div>
                </div>
                )}
              </div>

              <div className="profile-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('address')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('address') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  {/* <span className="section-icon">📍</span> */}
                  <span className="section-title">Address Information</span>
                </button>
                
                {expandedSections.has('address') && (
                <div className="profile-grid">
                  <div className="profile-field full-width">
                    <span className="field-label">Address:</span>
                    <span className="field-value">{user?.address || 'Not provided'}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">City:</span>
                    <span className="field-value">{user?.city || 'Not provided'}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">State:</span>
                    <span className="field-value">{user?.state || 'Not provided'}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">ZIP Code:</span>
                    <span className="field-value">{user?.zip || 'Not provided'}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">Country:</span>
                    <span className="field-value">{user?.country || 'Not provided'}</span>
                  </div>
                </div>
                )}
              </div>

              <div className="profile-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('subscription')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('subscription') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  <span className="section-title">Subscription & Plan</span>
                </button>
                
                {expandedSections.has('subscription') && (
                  <div className="profile-grid">
                    {loadingSubscription ? (
                      <div className="profile-field full-width">
                        <span className="field-value">Loading subscription details...</span>
                      </div>
                    ) : subscription ? (
                      <>
                        <div className="profile-field">
                          <span className="field-label">Current Plan:</span>
                          <span className={`field-value tier-badge tier-badge--${subscription.tier}`}>
                            {subscriptionService.getTierDisplayName(subscription.tier)}
                          </span>
                        </div>
                        <div className="profile-field">
                          <span className="field-label">Status:</span>
                          <span className={`field-value status ${subscription.isActive ? 'active' : 'inactive'}`}>
                            {subscription.status.charAt(0).toUpperCase() + subscription.status.slice(1)}
                          </span>
                        </div>
                        <div className="profile-field">
                          <span className="field-label">Max Brands:</span>
                          <span className="field-value">
                            {subscription.limits.maxBrands === -1 ? 'Unlimited' : subscription.limits.maxBrands}
                          </span>
                        </div>
                        <div className="profile-field">
                          <span className="field-label">Max Configs per Brand:</span>
                          <span className="field-value">
                            {subscription.limits.maxConfigsPerBrand === -1 ? 'Unlimited' : subscription.limits.maxConfigsPerBrand}
                          </span>
                        </div>
                        {subscription.currentPeriodEnd && (
                          <div className="profile-field">
                            <span className="field-label">Renewal Date:</span>
                            <span className="field-value">
                              {new Date(subscription.currentPeriodEnd).toLocaleDateString()}
                            </span>
                          </div>
                        )}
                        <div className="profile-field full-width">
                          <button 
                            className="btn btn-primary manage-subscription-btn" 
                            onClick={() => navigate('/subscription')}
                          >
                            {subscription.tier === 'free' ? 'Upgrade Plan' : 'Manage Subscription'}
                          </button>
                        </div>
                      </>
                    ) : (
                      <div className="profile-field full-width">
                        <span className="field-value">Unable to load subscription details</span>
                      </div>
                    )}
                  </div>
                )}
              </div>

              <div className="profile-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('account')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('account') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  {/* <span className="section-icon">🔑</span> */}
                  <span className="section-title">Account Details</span>
                </button>
                
                {expandedSections.has('account') && (
                <div className="profile-grid">
                  <div className="profile-field">
                    <span className="field-label">User ID:</span>
                    <span className="field-value">{user?.id}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">Auth0 ID:</span>
                    <span className="field-value">{user?.auth0Id}</span>
                  </div>
                  <div className="profile-field">
                    <span className="field-label">Member Since:</span>
                    <span className="field-value">{new Date(user?.createdAt || '').toLocaleDateString()}</span>
                  </div>
                </div>
                )}
              </div>

              <div className="profile-section">
                <button 
                  className="section-toggle"
                  onClick={() => toggleSection('brands')}
                >
                  <svg 
                    className={`chevron ${expandedSections.has('brands') ? 'open' : ''}`}
                    width="16" 
                    height="16" 
                    viewBox="0 0 16 16" 
                    fill="none"
                  >
                    <path d="M4 6L8 10L12 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  {/* <span className="section-icon">🏢</span> */}
                  <span className="section-title">Associated Brands</span>
                  {user?.brands && user?.brands.length > 0 && (
                    <span className="badge">{user.brands.length}</span>
                  )}
                </button>
                
                {expandedSections.has('brands') && (
                  <>
                  {user?.brands && user?.brands.length > 0 ? (
                  <div className="brands-list">
                    {user?.brands.map((brand) => (
                      <div key={brand.id} className="brand-item">
                        <div className="brand-info">
                          <h4 className="brand-name">{brand.name}</h4>
                          {brand.description && (
                            <p className="brand-description">{brand.description}</p>
                          )}
                          {brand.website && (
                            <a href={brand.website} target="_blank" rel="noopener noreferrer" className="brand-website">
                              {brand.website}
                            </a>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                  ) : (
                    <p className="empty-message">No brands associated with this account.</p>
                  )}
                  </>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// apps/dinoconfig-builder/src/app/components/profile/profile.component.ts
import { Component, signal, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { UserService } from '../../services/user.service';
import { SubscriptionService } from '../../services/subscription.service';
import { User } from '../../models/user.models';
import { SubscriptionStatus } from '../../models/subscription.models';
import { SpinnerComponent } from '../shared/spinner/spinner.component';
import { catchError, of } from 'rxjs';

@Component({
  selector: 'dc-profile',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatIconModule,
    SpinnerComponent
  ],
  templateUrl: './profile.component.html',
  styleUrl: './profile.component.scss'
})
export class ProfileComponent implements OnInit {
  private router = inject(Router);
  private userService = inject(UserService);
  private subscriptionService = inject(SubscriptionService);

  user = signal<User | null>(null);
  subscription = signal<SubscriptionStatus | null>(null);
  isLoading = signal(true);
  isLoadingSubscription = signal(true);
  error = signal<string | null>(null);
  
  expandedSections = signal<Set<string>>(new Set(['personal', 'address', 'account', 'subscription', 'brands']));

  ngOnInit(): void {
    this.loadUser();
    this.loadSubscription();
  }

  loadUser(): void {
    this.isLoading.set(true);
    this.error.set(null);

    this.userService.getUser().pipe(
      catchError((err: any) => {
        this.error.set(err.error?.message || 'Failed to load profile information');
        return of(null);
      })
    ).subscribe(data => {
      if (data) {
        this.user.set(data);
      }
      this.isLoading.set(false);
    });
  }

  loadSubscription(): void {
    this.isLoadingSubscription.set(true);

    this.subscriptionService.getSubscriptionWithViolations().pipe(
      catchError(() => of(null))
    ).subscribe(data => {
      if (data) {
        this.subscription.set({
          tier: data.tier,
          status: data.status,
          limits: data.limits,
          features: data.features,
          currentPeriodEnd: data.currentPeriodEnd,
          isActive: data.isActive
        });
      }
      this.isLoadingSubscription.set(false);
    });
  }

  refreshUser(): void {
    this.loadUser();
  }

  toggleSection(section: string): void {
    const current = new Set(this.expandedSections());
    if (current.has(section)) {
      current.delete(section);
    } else {
      current.add(section);
    }
    this.expandedSections.set(current);
  }

  isExpanded(section: string): boolean {
    return this.expandedSections().has(section);
  }

  getTierDisplayName(tier: string): string {
    return this.subscriptionService.getTierDisplayName(tier);
  }

  formatDate(date: Date | string | undefined): string {
    if (!date) return 'N/A';
    return new Date(date).toLocaleDateString();
  }

  goToSubscription(): void {
    this.router.navigate(['/subscription']);
  }
}

<div class="profile-page">
  <div class="main-layout">
    @if (isLoading()) {
      <div class="flex items-center justify-center min-h-screen">
        <dc-spinner text="Loading profile..." size="large" [fullHeight]="true"></dc-spinner>
      </div>
    } @else if (error()) {
      <div class="error-state">
        <h2>Error loading profile</h2>
        <p>{{ error() }}</p>
      </div>
    } @else {
      <div class="profile-header">
        <div class="header-content">
          <h1 class="page-title">User Profile</h1>
          <p class="page-subtitle">View and manage your account information</p>
        </div>
        <button 
          class="refresh-btn" 
          (click)="refreshUser()"
          [disabled]="isLoading()"
        >
          <mat-icon class="refresh-icon">refresh</mat-icon>
          {{ isLoading() ? 'Refreshing...' : 'Refresh Profile' }}
        </button>
      </div>

      <div class="main-content">
        <div class="profile-container">
          <div class="profile-content">
            
            <div class="profile-section">
              <button 
                class="section-toggle"
                (click)="toggleSection('personal')"
              >
                <mat-icon 
                  class="chevron"
                  [class.open]="isExpanded('personal')"
                >
                  expand_more
                </mat-icon>
                <span class="section-title">Personal Information</span>
              </button>
              
              @if (isExpanded('personal')) {
                <div class="profile-grid">
                  <div class="profile-field">
                    <span class="field-label">First Name:</span>
                    <span class="field-value">{{ user()?.firstName || 'N/A' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">Last Name:</span>
                    <span class="field-value">{{ user()?.lastName || 'N/A' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">Email:</span>
                    <span class="field-value">{{ user()?.email || 'N/A' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">Phone Number:</span>
                    <span class="field-value">{{ user()?.phoneNumber || 'Not provided' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">Company Name:</span>
                    <span class="field-value">{{ user()?.companyName || 'Not provided' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">Account Status:</span>
                    <span class="field-value status" [class.active]="user()?.isActive" [class.inactive]="!user()?.isActive">
                      {{ user()?.isActive ? 'Active' : 'Inactive' }}
                    </span>
                  </div>
                </div>
              }
            </div>

            <div class="profile-section">
              <button 
                class="section-toggle"
                (click)="toggleSection('address')"
              >
                <mat-icon 
                  class="chevron"
                  [class.open]="isExpanded('address')"
                >
                  expand_more
                </mat-icon>
                <span class="section-title">Address Information</span>
              </button>
              
              @if (isExpanded('address')) {
                <div class="profile-grid">
                  <div class="profile-field full-width">
                    <span class="field-label">Address:</span>
                    <span class="field-value">{{ user()?.address || 'Not provided' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">City:</span>
                    <span class="field-value">{{ user()?.city || 'Not provided' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">State:</span>
                    <span class="field-value">{{ user()?.state || 'Not provided' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">ZIP Code:</span>
                    <span class="field-value">{{ user()?.zip || 'Not provided' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">Country:</span>
                    <span class="field-value">{{ user()?.country || 'Not provided' }}</span>
                  </div>
                </div>
              }
            </div>

            <div class="profile-section">
              <button 
                class="section-toggle"
                (click)="toggleSection('subscription')"
              >
                <mat-icon 
                  class="chevron"
                  [class.open]="isExpanded('subscription')"
                >
                  expand_more
                </mat-icon>
                <span class="section-title">Subscription & Plan</span>
              </button>
              
              @if (isExpanded('subscription')) {
                <div class="profile-grid">
                  @if (isLoadingSubscription()) {
                    <div class="profile-field full-width">
                      <span class="field-value">Loading subscription details...</span>
                    </div>
                  } @else if (subscription()) {
                    <div class="profile-field">
                      <span class="field-label">Current Plan:</span>
                      <span class="field-value tier-badge" [class.tier-badge--free]="subscription()!.tier === 'free'" [class.tier-badge--pro]="subscription()!.tier === 'pro'" [class.tier-badge--custom]="subscription()!.tier === 'custom'">
                        {{ getTierDisplayName(subscription()!.tier) }}
                      </span>
                    </div>
                    <div class="profile-field">
                      <span class="field-label">Status:</span>
                      <span class="field-value status" [class.active]="subscription()!.isActive" [class.inactive]="!subscription()!.isActive">
                        {{ subscription()!.status.charAt(0).toUpperCase() + subscription()!.status.slice(1) }}
                      </span>
                    </div>
                    <div class="profile-field">
                      <span class="field-label">Max Brands:</span>
                      <span class="field-value">
                        {{ subscription()!.limits.maxBrands === -1 ? 'Unlimited' : subscription()!.limits.maxBrands }}
                      </span>
                    </div>
                    <div class="profile-field">
                      <span class="field-label">Max Configs per Brand:</span>
                      <span class="field-value">
                        {{ subscription()!.limits.maxConfigsPerBrand === -1 ? 'Unlimited' : subscription()!.limits.maxConfigsPerBrand }}
                      </span>
                    </div>
                    @if (subscription()!.currentPeriodEnd) {
                      <div class="profile-field">
                        <span class="field-label">Renewal Date:</span>
                        <span class="field-value">
                          {{ formatDate(subscription()!.currentPeriodEnd) }}
                        </span>
                      </div>
                    }
                    <div class="profile-field full-width">
                      <button 
                        class="manage-subscription-btn" 
                        (click)="goToSubscription()"
                      >
                        {{ subscription()!.tier === 'free' ? 'Upgrade Plan' : 'Manage Subscription' }}
                      </button>
                    </div>
                  } @else {
                    <div class="profile-field full-width">
                      <span class="field-value">Unable to load subscription details</span>
                    </div>
                  }
                </div>
              }
            </div>

            <div class="profile-section">
              <button 
                class="section-toggle"
                (click)="toggleSection('account')"
              >
                <mat-icon 
                  class="chevron"
                  [class.open]="isExpanded('account')"
                >
                  expand_more
                </mat-icon>
                <span class="section-title">Account Details</span>
              </button>
              
              @if (isExpanded('account')) {
                <div class="profile-grid">
                  <div class="profile-field">
                    <span class="field-label">User ID:</span>
                    <span class="field-value">{{ user()?.id || 'N/A' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">Auth0 ID:</span>
                    <span class="field-value">{{ user()?.auth0Id || 'N/A' }}</span>
                  </div>
                  <div class="profile-field">
                    <span class="field-label">Member Since:</span>
                    <span class="field-value">{{ formatDate(user()?.createdAt) }}</span>
                  </div>
                </div>
              }
            </div>

            <div class="profile-section">
              <button 
                class="section-toggle"
                (click)="toggleSection('brands')"
              >
                <mat-icon 
                  class="chevron"
                  [class.open]="isExpanded('brands')"
                >
                  expand_more
                </mat-icon>
                <span class="section-title">Associated Brands</span>
                @if (user()?.brands && user()!.brands.length > 0) {
                  <span class="badge">{{ user()!.brands.length }}</span>
                }
              </button>
              
              @if (isExpanded('brands')) {
                @if (user()?.brands && user()!.brands.length > 0) {
                  <div class="brands-list">
                    @for (brand of user()!.brands; track brand.id) {
                      <div class="brand-item">
                        <div class="brand-info">
                          <h4 class="brand-name">{{ brand.name }}</h4>
                          @if (brand.description) {
                            <p class="brand-description">{{ brand.description }}</p>
                          }
                          @if (brand.website) {
                            <a [href]="brand.website" target="_blank" rel="noopener noreferrer" class="brand-website">
                              {{ brand.website }}
                            </a>
                          }
                        </div>
                      </div>
                    }
                  </div>
                } @else {
                  <p class="empty-message">No brands associated with this account.</p>
                }
              }
            </div>

            <div class="profile-section danger-zone">
              <button 
                class="section-toggle"
                (click)="toggleSection('danger')"
              >
                <mat-icon 
                  class="chevron"
                  [class.open]="isExpanded('danger')"
                >
                  expand_more
                </mat-icon>
                <span class="section-title">Danger Zone</span>
              </button>
              @if (isExpanded('danger')) {
                <div class="danger-zone-content">
                  @if (closeAccountToast()) {
                    <p class="toast-success" role="status">{{ closeAccountToast() }}</p>
                  }
                  <p class="danger-description">Closing your account will deactivate it and schedule permanent deletion in 30 days. You can restore it during this period.</p>
                  <button 
                    type="button"
                    class="btn-close-account"
                    (click)="openCloseAccountModal()"
                  >
                    Close Account
                  </button>
                </div>
              }
            </div>
          </div>
        </div>
      </div>
    }
  </div>
</div>
