// apps/dinoconfig-builder/src/app/components/signup/signup.component.ts
import { Component, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule, AbstractControl, ValidationErrors } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { AuthLayoutComponent } from '../shared/auth-layout/auth-layout.component';

@Component({
  selector: 'dc-signup',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    RouterModule,
    AuthLayoutComponent,
  ],
  templateUrl: './signup.component.html',
  styleUrl: './signup.component.scss'
})
export class SignupComponent {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);

  // Signals for component state
  isLoading = signal(false);
  error = signal('');
  showPassword = signal(false);
  showConfirmPassword = signal(false);

  signupForm: FormGroup = this.fb.group({
    firstName: ['', [Validators.required, Validators.minLength(2)]],
    lastName: ['', [Validators.required, Validators.minLength(2)]],
    company: ['', [Validators.required, Validators.minLength(2)]],
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(8)]],
    confirmPassword: ['', [Validators.required]],
    agreeToTerms: [false, [Validators.requiredTrue]]
  }, {
    validators: this.passwordMatchValidator
  });

  passwordMatchValidator(control: AbstractControl): ValidationErrors | null {
    const password = control.get('password');
    const confirmPassword = control.get('confirmPassword');
    
    if (!password || !confirmPassword) {
      return null;
    }
    
    return password.value === confirmPassword.value ? null : { passwordMismatch: true };
  }

  getFieldError(fieldName: string): string {
    const field = this.signupForm.get(fieldName);
    if (!field || !field.errors || !field.touched) {
      return '';
    }

    if (field.errors['required']) {
      return `${fieldName.charAt(0).toUpperCase() + fieldName.slice(1)} is required`;
    }
    if (field.errors['minlength']) {
      const requiredLength = field.errors['minlength'].requiredLength;
      return `${fieldName.charAt(0).toUpperCase() + fieldName.slice(1)} must be at least ${requiredLength} characters`;
    }
    if (field.errors['email']) {
      return 'Please enter a valid email address';
    }
    if (field.errors['requiredTrue'] && fieldName === 'agreeToTerms') {
      return 'You must agree to the terms to continue';
    }
    return '';
  }

  getPasswordMismatchError(): string {
    if (this.signupForm.errors?.['passwordMismatch'] && 
        this.signupForm.get('confirmPassword')?.touched) {
      return 'Passwords do not match';
    }
    return '';
  }

  onSubmit(): void {
    if (this.signupForm.invalid) {
      // Mark all fields as touched to show errors
      Object.keys(this.signupForm.controls).forEach(key => {
        this.signupForm.get(key)?.markAsTouched();
      });
      return;
    }

    this.error.set('');
    this.isLoading.set(true);

    const { firstName, lastName, company, email, password } = this.signupForm.value;

    this.authService.signup({
      firstName,
      lastName,
      company,
      email,
      password
    }).subscribe({
      next: () => {
        this.isLoading.set(false);
        this.router.navigate(['/verify-email']);
      },
      error: (err: any) => {
        this.isLoading.set(false);
        let errorMessage = 'Signup failed. Please try again.';
        
        if (err.error?.message) {
          errorMessage = err.error.message;
        } else if (err.status === 409) {
          errorMessage = 'An account with this email already exists.';
        } else if (err.status === 0 || !err.status) {
          errorMessage = 'Unable to connect to server. Please check your connection.';
        }
        
        this.error.set(errorMessage);
      }
    });
  }

  togglePasswordVisibility(): void {
    this.showPassword.update(value => !value);
  }

  toggleConfirmPasswordVisibility(): void {
    this.showConfirmPassword.update(value => !value);
  }
}


<dc-auth-layout
  title="Create Account"
  description="Join DinoConfig and start managing your configurations"
  sidebarTitle="Start Your Journey"
  sidebarDescription="Join thousands of developers managing configurations with DinoConfig."
  maxWidth="500px"
  padding="p-6 md:p-8"
  [showOverflow]="true"
>
  @if (error()) {
    <div class="error-message">
      {{ error() }}
    </div>
  }

  <form [formGroup]="signupForm" (ngSubmit)="onSubmit()" class="auth-form">
    <div class="form-row">
      <div class="form-group">
        <label class="form-label">First Name</label>
        <input
          type="text"
          formControlName="firstName"
          placeholder="Enter your first name"
          class="form-input"
          [class.error]="getFieldError('firstName') && signupForm.get('firstName')?.touched"
          autocomplete="given-name"
        />
        @if (getFieldError('firstName') && signupForm.get('firstName')?.touched) {
          <span class="error-text">{{ getFieldError('firstName') }}</span>
        }
      </div>

      <div class="form-group">
        <label class="form-label">Last Name</label>
        <input
          type="text"
          formControlName="lastName"
          placeholder="Enter your last name"
          class="form-input"
          [class.error]="getFieldError('lastName') && signupForm.get('lastName')?.touched"
          autocomplete="family-name"
        />
        @if (getFieldError('lastName') && signupForm.get('lastName')?.touched) {
          <span class="error-text">{{ getFieldError('lastName') }}</span>
        }
      </div>
    </div>

    <div class="form-group">
      <label class="form-label">Company</label>
      <input
        type="text"
        formControlName="company"
        placeholder="Enter your company name"
        class="form-input"
        [class.error]="getFieldError('company') && signupForm.get('company')?.touched"
        autocomplete="organization"
      />
      @if (getFieldError('company') && signupForm.get('company')?.touched) {
        <span class="error-text">{{ getFieldError('company') }}</span>
      }
    </div>

    <div class="form-group">
      <label class="form-label">Email</label>
      <input
        type="email"
        formControlName="email"
        placeholder="Enter your email address"
        class="form-input"
        [class.error]="getFieldError('email') && signupForm.get('email')?.touched"
        autocomplete="email"
      />
      @if (getFieldError('email') && signupForm.get('email')?.touched) {
        <span class="error-text">{{ getFieldError('email') }}</span>
      }
    </div>

    <div class="form-group">
      <label class="form-label">Password</label>
      <div class="password-input-wrapper">
        <input
          [type]="showPassword() ? 'text' : 'password'"
          formControlName="password"
          placeholder="Create a strong password"
          class="form-input"
          [class.error]="getFieldError('password') && signupForm.get('password')?.touched"
          autocomplete="new-password"
        />
        <button
          type="button"
          class="password-toggle"
          (click)="togglePasswordVisibility()"
          [attr.aria-label]="showPassword() ? 'Hide password' : 'Show password'"
        >
          @if (showPassword()) {
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/>
              <line x1="1" y1="1" x2="23" y2="23"/>
            </svg>
          } @else {
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
              <circle cx="12" cy="12" r="3"/>
            </svg>
          }
        </button>
      </div>
      @if (getFieldError('password') && signupForm.get('password')?.touched) {
        <span class="error-text">{{ getFieldError('password') }}</span>
      }
    </div>

    <div class="form-group">
      <label class="form-label">Confirm Password</label>
      <div class="password-input-wrapper">
        <input
          [type]="showConfirmPassword() ? 'text' : 'password'"
          formControlName="confirmPassword"
          placeholder="Confirm your password"
          class="form-input"
          [class.error]="(getPasswordMismatchError() || getFieldError('confirmPassword')) && signupForm.get('confirmPassword')?.touched"
          autocomplete="new-password"
        />
        <button
          type="button"
          class="password-toggle"
          (click)="toggleConfirmPasswordVisibility()"
          [attr.aria-label]="showConfirmPassword() ? 'Hide password' : 'Show password'"
        >
          @if (showConfirmPassword()) {
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/>
              <line x1="1" y1="1" x2="23" y2="23"/>
            </svg>
          } @else {
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
              <circle cx="12" cy="12" r="3"/>
            </svg>
          }
        </button>
      </div>
      @if (getPasswordMismatchError() && signupForm.get('confirmPassword')?.touched) {
        <span class="error-text">{{ getPasswordMismatchError() }}</span>
      }
      @if (getFieldError('confirmPassword') && signupForm.get('confirmPassword')?.touched) {
        <span class="error-text">{{ getFieldError('confirmPassword') }}</span>
      }
    </div>

    <div class="checkbox-group">
      <label class="checkbox-label">
        <input
          type="checkbox"
          formControlName="agreeToTerms"
          class="checkbox-input"
        />
        <span class="checkbox-text">
          I agree to the
          <a href="#" class="checkbox-link">Terms of Service</a>
          and
          <a href="#" class="checkbox-link">Privacy Policy</a>
        </span>
      </label>
      @if (getFieldError('agreeToTerms') && signupForm.get('agreeToTerms')?.touched) {
        <span class="error-text">{{ getFieldError('agreeToTerms') }}</span>
      }
    </div>

    <button
      type="submit"
      class="btn btn-primary"
      [disabled]="isLoading() || signupForm.invalid"
    >
      @if (isLoading()) {
        <span class="spinner"></span>
        <span>Creating account...</span>
      } @else {
        Create Account
      }
    </button>
  </form>

  <div class="auth-footer">
    <p>
      Already have an account?
      <a routerLink="/signin" class="auth-link">Sign in</a>
    </p>
  </div>
</dc-auth-layout>

// apps/dinoconfig_builder/src/app/pages/SignUp.tsx
import { useState, FormEvent, useContext } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { authService } from '../services/auth.service';
import { AuthContext } from '../auth/auth-provider';
import './SignUp.scss';
import dinoconfigLogo from '../../assets/dinoconfig-logo.svg';

export default function SignUp() {
  const navigate = useNavigate();
  const { refreshAuth } = useContext(AuthContext);
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    company: '',
    email: '',
    password: '',
    confirmPassword: '',
    agreeToTerms: false,
  });
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});

  const validateForm = () => {
    const errors: Record<string, string> = {};

    if (formData.firstName.length < 2) {
      errors.firstName = 'First name must be at least 2 characters';
    }

    if (formData.lastName.length < 2) {
      errors.lastName = 'Last name must be at least 2 characters';
    }

    if (formData.company.length < 2) {
      errors.company = 'Company name must be at least 2 characters';
    }

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      errors.email = 'Please enter a valid email address';
    }

    if (formData.password.length < 8) {
      errors.password = 'Password must be at least 8 characters';
    }

    if (formData.password !== formData.confirmPassword) {
      errors.confirmPassword = 'Passwords do not match';
    }

    if (!formData.agreeToTerms) {
      errors.agreeToTerms = 'You must agree to the terms to continue';
    }

    setFieldErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError('');
    setFieldErrors({});

    if (!validateForm()) {
      return;
    }

    setIsLoading(true);

    try {
      await authService.signup({
        firstName: formData.firstName,
        lastName: formData.lastName,
        company: formData.company,
        email: formData.email,
        password: formData.password,
      });
      await refreshAuth();
      // User will be loaded automatically by UserProvider when isAuthenticated becomes true
      navigate('/brands');
    } catch (err: any) {
      let errorMessage = 'Signup failed. Please try again.';
      
      if (err.response?.data?.message) {
        errorMessage = err.response.data.message;
      } else if (err.response?.status === 409) {
        errorMessage = 'An account with this email already exists.';
      } else if (err.response?.status === 0 || !err.response) {
        errorMessage = 'Unable to connect to server. Please check your connection.';
      }
      
      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  const handleChange = (field: string, value: string | boolean) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear field error when user starts typing
    if (fieldErrors[field]) {
      setFieldErrors((prev) => {
        const newErrors = { ...prev };
        delete newErrors[field];
        return newErrors;
      });
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-container">
        <div className="auth-form-section">
          <div className="auth-form-wrapper">
            <div className="auth-header">
              <h1 className="page-title">Create Account</h1>
              <p>Join DinoConfig and start managing your configurations</p>
            </div>

            {error && (
              <div className="error-message">
                {error}
              </div>
            )}

            <form onSubmit={handleSubmit} className="auth-form">
              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="firstName">First Name</label>
                  <input
                    id="firstName"
                    type="text"
                    value={formData.firstName}
                    onChange={(e) => handleChange('firstName', e.target.value)}
                    placeholder="Enter your first name"
                    required
                    autoComplete="given-name"
                  />
                  {fieldErrors.firstName && (
                    <span className="field-error">{fieldErrors.firstName}</span>
                  )}
                </div>

                <div className="form-group">
                  <label htmlFor="lastName">Last Name</label>
                  <input
                    id="lastName"
                    type="text"
                    value={formData.lastName}
                    onChange={(e) => handleChange('lastName', e.target.value)}
                    placeholder="Enter your last name"
                    required
                    autoComplete="family-name"
                  />
                  {fieldErrors.lastName && (
                    <span className="field-error">{fieldErrors.lastName}</span>
                  )}
                </div>
              </div>

              <div className="form-group">
                <label htmlFor="company">Company</label>
                <input
                  id="company"
                  type="text"
                  value={formData.company}
                  onChange={(e) => handleChange('company', e.target.value)}
                  placeholder="Enter your company name"
                  required
                  autoComplete="organization"
                />
                {fieldErrors.company && (
                  <span className="field-error">{fieldErrors.company}</span>
                )}
              </div>

              <div className="form-group">
                <label htmlFor="email">Email</label>
                <input
                  id="email"
                  type="email"
                  value={formData.email}
                  onChange={(e) => handleChange('email', e.target.value)}
                  placeholder="Enter your email address"
                  required
                  autoComplete="email"
                />
                {fieldErrors.email && (
                  <span className="field-error">{fieldErrors.email}</span>
                )}
              </div>

              <div className="form-group">
                <label htmlFor="password">Password</label>
                <div className="password-input-wrapper">
                  <input
                    id="password"
                    type={showPassword ? 'text' : 'password'}
                    value={formData.password}
                    onChange={(e) => handleChange('password', e.target.value)}
                    placeholder="Create a strong password"
                    required
                    autoComplete="new-password"
                  />
                  <button
                    type="button"
                    className="password-toggle"
                    onClick={() => setShowPassword(!showPassword)}
                    aria-label={showPassword ? 'Hide password' : 'Show password'}
                  >
                    {showPassword ? (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path>
                        <line x1="1" y1="1" x2="23" y2="23"></line>
                      </svg>
                    ) : (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                        <circle cx="12" cy="12" r="3"></circle>
                      </svg>
                    )}
                  </button>
                </div>
                {fieldErrors.password && (
                  <span className="field-error">{fieldErrors.password}</span>
                )}
              </div>

              <div className="form-group">
                <label htmlFor="confirmPassword">Confirm Password</label>
                <div className="password-input-wrapper">
                  <input
                    id="confirmPassword"
                    type={showConfirmPassword ? 'text' : 'password'}
                    value={formData.confirmPassword}
                    onChange={(e) => handleChange('confirmPassword', e.target.value)}
                    placeholder="Confirm your password"
                    required
                    autoComplete="new-password"
                  />
                  <button
                    type="button"
                    className="password-toggle"
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    aria-label={showConfirmPassword ? 'Hide password' : 'Show password'}
                  >
                    {showConfirmPassword ? (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path>
                        <line x1="1" y1="1" x2="23" y2="23"></line>
                      </svg>
                    ) : (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                        <circle cx="12" cy="12" r="3"></circle>
                      </svg>
                    )}
                  </button>
                </div>
                {fieldErrors.confirmPassword && (
                  <span className="field-error">{fieldErrors.confirmPassword}</span>
                )}
              </div>

              <div className="form-group">
                <label className="checkbox-label">
                  <input
                    type="checkbox"
                    checked={formData.agreeToTerms}
                    onChange={(e) => handleChange('agreeToTerms', e.target.checked)}
                  />
                  <span>
                    I agree to the{' '}
                    <a href="#" className="terms-link">Terms of Service</a>
                    {' '}and{' '}
                    <a href="#" className="terms-link">Privacy Policy</a>
                  </span>
                </label>
                {fieldErrors.agreeToTerms && (
                  <span className="field-error">{fieldErrors.agreeToTerms}</span>
                )}
              </div>

              <button
                type="submit"
                className="submit-button"
                disabled={isLoading}
              >
                {isLoading ? (
                  <span className="button-loading">
                    <span className="spinner"></span>
                    Creating account...
                  </span>
                ) : (
                  'Create Account'
                )}
              </button>
            </form>

            <div className="auth-footer">
              <p>
                Already have an account?{' '}
                <Link to="/signin" className="auth-link">
                  Sign in
                </Link>
              </p>
            </div>
          </div>
        </div>

        <div className="auth-visual-section">
          <div className="visual-content">
            <div className="logo-container">
              <img src={dinoconfigLogo} alt="DinoConfig" className="logo" />
            </div>
            <div className="visual-text">
              <h2>Start Your Journey</h2>
              <p>Join thousands of developers managing configurations with DinoConfig.</p>
            </div>
            <div className="visual-decoration">
              <div className="decoration-circle circle-1"></div>
              <div className="decoration-circle circle-2"></div>
              <div className="decoration-circle circle-3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
