// apps/dinoconfig_builder/src/app/pages/ForgotPassword.tsx
import { useState, FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { authService } from '../services/auth.service';
import './ForgotPassword.scss';
import dinoconfigLogo from '../../assets/dinoconfig-logo.svg';

export default function ForgotPassword() {
  const [email, setEmail] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccessMessage('');
    setIsLoading(true);

    try {
      await authService.forgotPassword(email);
      setSuccessMessage('Password reset email sent. Please check your inbox.');
    } catch (err: any) {
      let errorMessage = 'Failed to send password reset email. Please try again.';
      
      if (err.response?.data?.message) {
        errorMessage = err.response.data.message;
      } else if (err.response?.status === 0 || !err.response) {
        errorMessage = 'Unable to connect to server. Please check your connection.';
      }
      
      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-container">
        <div className="auth-form-section">
          <div className="auth-form-wrapper">
            <div className="auth-header">
              <h1 className="page-title">Reset Password</h1>
              <p>Enter your email to receive a password reset link</p>
            </div>

            {error && (
              <div className="error-message">
                {error}
              </div>
            )}

            {successMessage && (
              <div className="success-message">
                {successMessage}
              </div>
            )}

            <form onSubmit={handleSubmit} className="auth-form">
              <div className="form-group">
                <label htmlFor="email">Email</label>
                <input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email"
                  required
                  autoComplete="email"
                />
              </div>

              <button
                type="submit"
                className="submit-button"
                disabled={isLoading}
              >
                {isLoading ? (
                  <span className="button-loading">
                    <span className="spinner"></span>
                    Sending...
                  </span>
                ) : (
                  'Send Reset Link'
                )}
              </button>
            </form>

            <div className="auth-footer">
              <p>
                Remember your password?{' '}
                <Link to="/signin" className="auth-link">
                  Sign in
                </Link>
              </p>
            </div>
          </div>
        </div>

        <div className="auth-visual-section">
          <div className="visual-content">
            <div className="logo-container">
              <img src={dinoconfigLogo} alt="DinoConfig" className="logo" />
            </div>
            <div className="visual-text">
              <h2>Reset Your Password</h2>
              <p>We'll send you a link to reset your password securely.</p>
            </div>
            <div className="visual-decoration">
              <div className="decoration-circle circle-1"></div>
              <div className="decoration-circle circle-2"></div>
              <div className="decoration-circle circle-3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// apps/dinoconfig-builder/src/app/components/forgot-password/forgot-password.component.ts
import { Component, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'dc-forgot-password',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './forgot-password.component.html',
  styleUrl: './forgot-password.component.scss'
})
export class ForgotPasswordComponent {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);

  // Signals for component state
  isLoading = signal(false);
  error = signal('');
  successMessage = signal('');

  forgotPasswordForm: FormGroup = this.fb.group({
    email: ['', [Validators.required, Validators.email]]
  });

  onSubmit(): void {
    if (this.forgotPasswordForm.invalid) {
      return;
    }

    this.error.set('');
    this.successMessage.set('');
    this.isLoading.set(true);

    const { email } = this.forgotPasswordForm.value;

    this.authService.forgotPassword(email).subscribe({
      next: () => {
        this.isLoading.set(false);
        this.successMessage.set('Password reset email sent. Please check your inbox.');
      },
      error: (err: any) => {
        this.isLoading.set(false);
        let errorMessage = 'Failed to send password reset email. Please try again.';
        
        if (err.error?.message) {
          errorMessage = err.error.message;
        } else if (err.status === 0 || !err.status) {
          errorMessage = 'Unable to connect to server. Please check your connection.';
        }
        
        this.error.set(errorMessage);
      }
    });
  }
}


<div class="auth-page">
  <div class="auth-container">
    <div class="auth-form-section">
      <div class="auth-form-wrapper">
        <div class="auth-header">
          <h1 class="page-title">Reset Password</h1>
          <p>Enter your email to receive a password reset link</p>
        </div>

        @if (error()) {
          <div class="error-message">
            {{ error() }}
          </div>
        }

        @if (successMessage()) {
          <div class="success-message">
            {{ successMessage() }}
          </div>
        }

        <form [formGroup]="forgotPasswordForm" (ngSubmit)="onSubmit()" class="auth-form">
          <div class="form-group">
            <label for="email">Email</label>
            <input
              id="email"
              type="email"
              formControlName="email"
              placeholder="Enter your email"
              required
              autocomplete="email"
            />
          </div>

          <button
            type="submit"
            class="submit-button"
            [disabled]="isLoading() || forgotPasswordForm.invalid"
          >
            @if (isLoading()) {
              <span class="button-loading">
                <span class="spinner"></span>
                Sending...
              </span>
            } @else {
              Send Reset Link
            }
          </button>
        </form>

        <div class="auth-footer">
          <p>
            Remember your password?
            <a routerLink="/signin" class="auth-link">
              Sign in
            </a>
          </p>
        </div>
      </div>
    </div>

    <div class="auth-visual-section">
      <div class="visual-content">
        <div class="logo-container">
          <img src="/assets/dinoconfig-logo.svg" alt="DinoConfig" class="logo" />
        </div>
        <div class="visual-text">
          <h2>Reset Your Password</h2>
          <p>We'll send you a link to reset your password securely.</p>
        </div>
        <div class="visual-decoration">
          <div class="decoration-circle circle-1"></div>
          <div class="decoration-circle circle-2"></div>
          <div class="decoration-circle circle-3"></div>
        </div>
      </div>
    </div>
  </div>
</div>
