// apps/dinoconfig-builder/src/app/components/form-elements/radio-group-element/radio-group-element.component.ts
import { Component, input, output, computed } from '@angular/core';

import { MatRadioModule } from '@angular/material/radio';
import { FormsModule } from '@angular/forms';
import { GridFieldConfig } from '../../../models/config.models';
import { BaseFormElementComponent } from '../base-form-element/base-form-element.component';

@Component({
  selector: 'dc-radio-group-element',
  standalone: true,
  imports: [MatRadioModule, FormsModule, BaseFormElementComponent],
  templateUrl: './radio-group-element.component.html',
  styleUrl: './radio-group-element.component.scss'
})
export class RadioGroupElementComponent {
  config = input.required<GridFieldConfig>();
  value = input<any>();
  isEditable = input<boolean>(true);
  valueChange = output<any>();
  edit = output<void>();
  delete = output<void>();

  options = computed(() => {
    const opts = this.config().options;
    return opts
      ? opts.split(',').map(o => o.trim()).filter(Boolean)
      : [];
  });

  onValueChange(event: any): void {
    const newValue = event?.value ?? event;
    this.valueChange.emit(newValue);
  }
}


<dc-base-form-element
  [config]="config()"
  [isEditable]="isEditable()"
  (edit)="edit.emit()"
  (delete)="delete.emit()"
>
  <div class="radio-group-wrapper">
    <label class="form-label">
      {{ config().label || config().name }}
      @if (config().required) {
        <span class="required-indicator">*</span>
      }
    </label>
    <mat-radio-group
      [value]="value() || ''"
      (change)="onValueChange($event.value)"
      [required]="config().required ?? false"
      class="radio-group"
    >
      @for (option of options(); track option) {
        <mat-radio-button [value]="option">
          {{ option }}
        </mat-radio-button>
      }
    </mat-radio-group>
    @if (config().required) {
      <div class="required-hint">* Required</div>
    }
  </div>
</dc-base-form-element>

// apps/dinoconfig_builder/src/app/components/formElements/RadioGroupElement.tsx
import React from 'react';
import { BaseFormElementProps, FormElementWrapper } from './BaseFormElement';

interface RadioGroupElementProps extends BaseFormElementProps {
  onEdit?: () => void;
  onDelete?: () => void;
}

export default function RadioGroupElement({ 
  config, 
  value, 
  onChange, 
  onEdit, 
  onDelete,
  isEditable = true 
}: RadioGroupElementProps) {
  const options = config.options ? config.options.split(',').map(o => o.trim()).filter(Boolean) : [];

  return (
    <FormElementWrapper config={config} onEdit={onEdit} onDelete={onDelete} isEditable={isEditable}>
      <div className="radio-group">
        {options.map((option, index) => (
          <label key={index} className="radio-label">
            <input
              type="radio"
              name={config.name}
              value={option}
              checked={value === option}
              onChange={(e) => onChange?.(e.target.value)}
              required={config.required}
              className="form-radio"
            />
            <span className="radio-text">{option}</span>
          </label>
        ))}
      </div>
    </FormElementWrapper>
  );
}
